# 1단계 1차 모집단 수집

`approved + candidate` 소스를 사용해 첫 공고 스냅샷을 수집하고 `staging`에 적재한다. 이 단계에서는 `master`를 갱신하지 않는다.

In [1]:
from IPython.display import display
import json
import pandas as pd

from jobs_market_v2.pipelines import build_coverage_report_pipeline, collect_jobs_pipeline, verify_sources_pipeline
from jobs_market_v2.settings import get_paths

paths = get_paths()
verify_summary = verify_sources_pipeline()
collect_summary = collect_jobs_pipeline(dry_run=False)
coverage_summary = build_coverage_report_pipeline()
verify_summary, collect_summary, coverage_summary

({'collected_job_count': 8,
  'verified_source_success_count': 12,
  'verified_source_failure_count': 0},
 {'collected_job_count': 8,
  'verified_source_success_count': 12,
  'verified_source_failure_count': 0,
  'quality_gate_passed': True,
  'quality_gate_reasons': []},
 {'발견 기업 수': 12,
  '층별 발견 기업 수': {'대기업': 2,
   '스타트업': 2,
   '중견/중소': 2,
   '공공·연구기관': 2,
   '외국계 한국법인': 2,
   '지역기업': 2},
  '공식 도메인 검증 성공 수': 12,
  '층별 공식 도메인 검증 성공 수': {'대기업': 2,
   '스타트업': 2,
   '중견/중소': 2,
   '공공·연구기관': 2,
   '외국계 한국법인': 2,
   '지역기업': 2},
  '공식 채용 소스 검증 성공 수': 12,
  'discovery source 유형별 성공률': {'html_page': 1.0,
   'json_api': 1.0,
   'official_careers': 1.0,
   'rss': 1.0},
  '비기업 엔티티 제거 수': 19,
  'quarantine source 수': 0,
  '활성 공고 수': 8,
  '직무별 공고 수': {'데이터 분석가': 2, '데이터 사이언티스트': 3, '인공지능 리서처': 1, '인공지능 엔지니어': 2},
  '신규/유지/변경/미발견 수': {'신규': 8, '유지': 0, '변경': 0, '미발견': 0},
  'HHI': 0.125,
  'top5 집중도': 0.625})

In [2]:
staging = pd.read_csv(paths.staging_jobs_path)
display(staging.head())

print(paths.first_snapshot_path)
print(paths.coverage_report_path)
print(json.dumps(json.loads(paths.coverage_report_path.read_text(encoding='utf-8')), ensure_ascii=False, indent=2))

,job_key,change_hash,first_seen_at,last_seen_at,is_active,missing_count,snapshot_date,run_id,source_url,source_bucket,...,상세본문_분석용,회사명_표시,소스명_표시,공고제목_표시,경력수준_표시,직무명_표시,주요업무_표시,자격요건_표시,우대사항_표시,핵심기술_표시
0,c8b346ba1b4a395080ec92c192969a37001441249660ba...,7cd06cc1f0c80a16720df0eb0b412f512b8b6bb592f46e...,2026-03-29T20:09:40+09:00,2026-03-29T20:09:40+09:00,True,0,2026-03-29,collect-jobs-20260329200940,https://careers.samsung.com/job-feed/data-ai.json,approved,...,주요업무\n서비스 지표를 분석합니다.\n실험 결과를 해석합니다.\n자격요건\n에스큐...,삼성전자,삼성전자 공식 채용,데이터 분석가,경력,데이터 분석가,서비스 지표를 분석합니다.\n실험 결과를 해석합니다.,에스큐엘 활용 경험\n통계 기반 분석 역량,에이비 테스트 경험,파이썬\n에스큐엘
1,31f51e51328b76d4c76d35685ba68f20eb8d89568aad23...,715147bc21417165d0bc39d13e46059596ee574321f175...,2026-03-29T20:09:40+09:00,2026-03-29T20:09:40+09:00,True,0,2026-03-29,collect-jobs-20260329200940,https://careers.navercorp.com/jobs/data-ai.html,approved,...,주요업무\n추천 모델을 실험합니다.\n서비스 품질을 계량적으로 평가합니다.\n자격요...,네이버,네이버 커리어,데이터 사이언티스트,경력,데이터 사이언티스트,추천 모델을 실험합니다.\n서비스 품질을 계량적으로 평가합니다.,머신러닝 모델링 경험\n데이터 파이프라인 이해,대규모 서비스 경험,파이썬\n머신러닝
2,5801f2ee4369022ac08d2e206af6f50f44ec8895f35303...,c515b38dd81672000025ec16102720d013cf5a14d77f5b...,2026-03-29T20:09:40+09:00,2026-03-29T20:09:40+09:00,True,0,2026-03-29,collect-jobs-20260329200940,https://career.daangn.com/jobs/data-ai.html,approved,...,주요업무\n추천 및 검색 모델을 서비스에 적용합니다.\n자격요건\n모델 배포 경험\...,당근,당근 채용,인공지능 엔지니어,경력,인공지능 엔지니어,추천 및 검색 모델을 서비스에 적용합니다.,모델 배포 경험\n실험 자동화 경험,대규모 로그 처리 경험,파이토치\n엠엘옵스
3,0958a194c775bf2f92caa940f56d8626e5bdac52719090...,a4fc9638227941cdf888af6ccc8ac7b8e9fb0c89a1ba4d...,2026-03-29T20:09:40+09:00,2026-03-29T20:09:40+09:00,True,0,2026-03-29,collect-jobs-20260329200940,https://careers.tmaxsoft.com/jobs/data-ai.html,approved,...,주요업무\n산업 데이터 기반 예측 모델을 개발합니다.\n자격요건\n시계열 분석 경험...,티맥스소프트,티맥스소프트 채용,데이터 사이언티스트,경력,데이터 사이언티스트,산업 데이터 기반 예측 모델을 개발합니다.,시계열 분석 경험\n실무형 모델 운영 경험,제조업 데이터 경험,파이썬\n통계모델링
4,d21e9ac2f4b287af5988ef3cf1971a0f6a48cdb56175cb...,0318e3b880326c8ee3eda3b506f2c8f595b0d65283165a...,2026-03-29T20:09:40+09:00,2026-03-29T20:09:40+09:00,True,0,2026-03-29,collect-jobs-20260329200940,https://recruit.etri.re.kr/rss/research-jobs.xml,approved,...,주요업무\n차세대 인공지능 알고리즘을 연구합니다.\n자격요건\n연구 논문 작성 경험...,한국전자통신연구원,한국전자통신연구원 연구채용,인공지능 리서처,경력,인공지능 리서처,차세대 인공지능 알고리즘을 연구합니다.,연구 논문 작성 경험\n실험 설계 역량,국책과제 경험,딥러닝\n실험설계

/Users/junheelee/Desktop/sctaper_p1/jobs_market_v2/output_samples/first_snapshot_jobs.parquet
/Users/junheelee/Desktop/sctaper_p1/jobs_market_v2/runtime/coverage_report.json
{
  "발견 기업 수": 12,
  "층별 발견 기업 수": {
    "대기업": 2,
    "스타트업": 2,
    "중견/중소": 2,
    "공공·연구기관": 2,
    "외국계 한국법인": 2,
    "지역기업": 2
  },
  "공식 도메인 검증 성공 수": 12,
  "층별 공식 도메인 검증 성공 수": {
    "대기업": 2,
    "스타트업": 2,
    "중견/중소": 2,
    "공공·연구기관": 2,
    "외국계 한국법인": 2,
    "지역기업": 2
  },
  "공식 채용 소스 검증 성공 수": 12,
  "discovery source 유형별 성공률": {
    "html_page": 1.0,
    "json_api": 1.0,
    "official_careers": 1.0,
    "rss": 1.0
  },
  "비기업 엔티티 제거 수": 19,
  "quarantine source 수": 0,
  "활성 공고 수": 8,
  "직무별 공고 수": {
    "데이터 분석가": 2,
    "데이터 사이언티스트": 3,
    "인공지능 리서처": 1,
    "인공지능 엔지니어": 2
  },
  "신규/유지/변경/미발견 수": {
    "신규": 8,
    "유지": 0,
    "변경": 0,
    "미발견": 0
  },
  "HHI": 0.125,
  "top5 집중도": 0.625
}

## 표시값, 분석용, 원문 비교 보기

`display`, `분석용`, `raw/detail` 기반 긴 텍스트를 같은 행에서 비교한다. 전처리 손실이 어느 단계에서 생겼는지 바로 확인할 수 있다.

In [3]:
import json
import pandas as pd
from IPython.display import display

from jobs_market_v2.html_utils import clean_html_text
from jobs_market_v2.settings import get_paths

paths = get_paths()
staging = pd.read_csv(paths.staging_jobs_path)
raw_detail = pd.read_json(paths.raw_detail_path, lines=True)


def pick(payload, *keys):
    if not isinstance(payload, dict):
        return ""
    for key in keys:
        value = payload.get(key, "")
        if value:
            return value
    return ""

raw_columns = ["job_key", "주요업무_raw", "자격요건_raw", "우대사항_raw", "핵심기술_raw", "상세본문_raw"]
if raw_detail.empty or "raw_payload_json" not in raw_detail.columns:
    compare_df = pd.DataFrame(columns=raw_columns)
else:
    raw_detail["raw_payload"] = raw_detail["raw_payload_json"].apply(json.loads)
    compare_df = raw_detail.copy()
    compare_df["주요업무_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "responsibilities", "main_tasks", "description_html", "description"))
    compare_df["자격요건_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "requirements", "description_html", "description"))
    compare_df["우대사항_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "preferred", "description_html", "description"))
    compare_df["핵심기술_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "core_skills", "skills", "description_html", "description"))
    compare_df["상세본문_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "description_html", "description"))

    for col in ["주요업무_raw", "자격요건_raw", "우대사항_raw", "핵심기술_raw", "상세본문_raw"]:
        compare_df[col] = compare_df[col].fillna("").apply(clean_html_text)

comparison_view = staging.merge(
    compare_df[["job_key", "주요업무_raw", "자격요건_raw", "우대사항_raw", "핵심기술_raw", "상세본문_raw"]],
    on="job_key",
    how="left",
)

comparison_view = comparison_view[[
    "회사명_표시",
    "공고제목_표시",
    "직무명_표시",
    "주요업무_표시",
    "주요업무_분석용",
    "주요업무_raw",
    "자격요건_표시",
    "자격요건_분석용",
    "자격요건_raw",
    "우대사항_표시",
    "우대사항_분석용",
    "우대사항_raw",
    "핵심기술_표시",
    "핵심기술_분석용",
    "핵심기술_raw",
    "상세본문_분석용",
    "상세본문_raw",
]]

display(comparison_view.head(20))

,회사명_표시,공고제목_표시,직무명_표시,주요업무_표시,주요업무_분석용,주요업무_raw,자격요건_표시,자격요건_분석용,자격요건_raw,우대사항_표시,우대사항_분석용,우대사항_raw,핵심기술_표시,핵심기술_분석용,핵심기술_raw,상세본문_분석용,상세본문_raw
0,삼성전자,데이터 분석가,데이터 분석가,서비스 지표를 분석합니다.\n실험 결과를 해석합니다.,서비스 지표를 분석합니다.\n실험 결과를 해석합니다.,주요업무\n서비스 지표를 분석합니다.\n실험 결과를 해석합니다.\n자격요건\nSQL...,에스큐엘 활용 경험\n통계 기반 분석 역량,에스큐엘 활용 경험\n통계 기반 분석 역량,주요업무\n서비스 지표를 분석합니다.\n실험 결과를 해석합니다.\n자격요건\nSQL...,에이비 테스트 경험,에이비 테스트 경험,주요업무\n서비스 지표를 분석합니다.\n실험 결과를 해석합니다.\n자격요건\nSQL...,파이썬\n에스큐엘,파이썬\n에스큐엘,주요업무\n서비스 지표를 분석합니다.\n실험 결과를 해석합니다.\n자격요건\nSQL...,주요업무\n서비스 지표를 분석합니다.\n실험 결과를 해석합니다.\n자격요건\n에스큐...,주요업무\n서비스 지표를 분석합니다.\n실험 결과를 해석합니다.\n자격요건\nSQL...
1,네이버,데이터 사이언티스트,데이터 사이언티스트,추천 모델을 실험합니다.\n서비스 품질을 계량적으로 평가합니다.,추천 모델을 실험합니다.\n서비스 품질을 계량적으로 평가합니다.,주요업무\n추천 모델을 실험합니다.\n서비스 품질을 계량적으로 평가합니다.\n자격요...,머신러닝 모델링 경험\n데이터 파이프라인 이해,머신러닝 모델링 경험\n데이터 파이프라인 이해,머신러닝 모델링 경험\n데이터 파이프라인 이해,대규모 서비스 경험,대규모 서비스 경험,대규모 서비스 경험,파이썬\n머신러닝,파이썬\n머신러닝,파이썬\n머신러닝,주요업무\n추천 모델을 실험합니다.\n서비스 품질을 계량적으로 평가합니다.\n자격요...,주요업무\n추천 모델을 실험합니다.\n서비스 품질을 계량적으로 평가합니다.\n자격요...
2,당근,인공지능 엔지니어,인공지능 엔지니어,추천 및 검색 모델을 서비스에 적용합니다.,추천 및 검색 모델을 서비스에 적용합니다.,주요업무\n추천 및 검색 모델을 서비스에 적용합니다.\n자격요건\n모델 배포 경험\...,모델 배포 경험\n실험 자동화 경험,모델 배포 경험\n실험 자동화 경험,모델 배포 경험\n실험 자동화 경험,대규모 로그 처리 경험,대규모 로그 처리 경험,대규모 로그 처리 경험,파이토치\n엠엘옵스,파이토치\n엠엘옵스,파이토치\nMLOps,주요업무\n추천 및 검색 모델을 서비스에 적용합니다.\n자격요건\n모델 배포 경험\...,주요업무\n추천 및 검색 모델을 서비스에 적용합니다.\n자격요건\n모델 배포 경험\...
3,티맥스소프트,데이터 사이언티스트,데이터 사이언티스트,산업 데이터 기반 예측 모델을 개발합니다.,산업 데이터 기반 예측 모델을 개발합니다.,주요업무\n산업 데이터 기반 예측 모델을 개발합니다.\n자격요건\n시계열 분석 경험...,시계열 분석 경험\n실무형 모델 운영 경험,시계열 분석 경험\n실무형 모델 운영 경험,시계열 분석 경험\n실무형 모델 운영 경험,제조업 데이터 경험,제조업 데이터 경험,제조업 데이터 경험,파이썬\n통계모델링,파이썬\n통계모델링,파이썬\n통계모델링,주요업무\n산업 데이터 기반 예측 모델을 개발합니다.\n자격요건\n시계열 분석 경험...,주요업무\n산업 데이터 기반 예측 모델을 개발합니다.\n자격요건\n시계열 분석 경험...
4,한국전자통신연구원,인공지능 리서처,인공지능 리서처,차세대 인공지능 알고리즘을 연구합니다.,차세대 인공지능 알고리즘을 연구합니다.,주요업무\n차세대 인공지능 알고리즘을 연구합니다.\n자격요건\n연구 논문 작성 경험...,연구 논문 작성 경험\n실험 설계 역량,연구 논문 작성 경험\n실험 설계 역량,연구 논문 작성 경험\n실험 설계 역량,국책과제 경험,국책과제 경험,국책과제 경험,딥러닝\n실험설계,딥러닝\n실험설계,딥러닝\n실험설계,주요업무\n차세대 인공지능 알고리즘을 연구합니다.\n자격요건\n연구 논문 작성 경험...,주요업무\n차세대 인공지능 알고리즘을 연구합니다.\n자격요건\n연구 논문 작성 경험...
5,선보공업,인공지능 엔지니어,인공지능 엔지니어,현장 설비 데이터를 활용해 예지보전 모델을 운영합니다.,현장 설비 데이터를 활용해 예지보전 모델을 운영합니다.,주요업무\n현장 설비 데이터를 활용해 예지보전 모델을 운영합니다.\n자격요건\n모델...,모델 서비스 운영 경험,모델 서비스 운영 경험,모델 서비스 운영 경험,지역 제조업 협업 경험,지역 제조업 협업 경험,지역 제조업 협업 경험,파이썬\n시계열 모델링,파이썬\n시계열 모델링,파이썬\n시계열 모델링,주요업무\n현장 설비 데이터를 활용해 예지보전 모델을 운영합니다.\n자격요건\n모델...,주요업무\n현장 설비 데이터를 활용해 예지보전 모델을 운영합니다.\n자격요건\n모델...
6,한국마이크로소프트,데이터 사이언티스트,데이터 사이언티스트,국내 고객 문제를 데이터로 정의합니다.,국내 고객 문제를 데이터로 정의합니다.,주요업무\n국내 고객 문제를 데이터로 정의합니다.\n자격요건\n머신러닝 모델 개발 ...,머신러닝 모델 개발 경험,머신러닝 모델 개발 경험,주요업무\n국내 고객 문제를 데이터로 정의합니다.\n자격요건\n머신러닝 모델 개발 ...,클라우드 경험,클라우드 경험,주요업무\n국내 고객 문제를 데이터로 정의합니다.\n자격요건\n머신러닝 모델 개발 ...,파이썬\n클라우드 머신러닝,파이썬\n클라우드 머신러닝,주요업무\n국내 고객 문제를 데이터로 정의합니다.\n자격요건\n머신러닝 모델 개발 ...,주요업무\n국내 고객 문제를 데이터로 정의합니다.\n자격요건\n머신러닝 모델 개발 ...,주요업무\n국내 고객 문제를 데이터로 정의합니다.\n자격요건\n머신러닝 모델 개발 ...
7,보쉬코리아,데이터 분석가,데이터 분석가,생산 데이터를 분석하고 품질 이슈를 탐지합니다.,생산 데이터를 분석하고 품질 이슈를 탐지합니다.,주요업무\n생산 데이터를 분석하고 품질 이슈를 탐지합니다.\n자격요건\n제조 데이터...,제조 데이터 분석 경험,제조 데이터 분석 경험,제조 데이터 분석 경험,품질 관리 경험,품질 관리 경험,품질 관리 경험,에스큐엘\n시각화,에스큐엘\n시각화,SQL\n시각화,주요업무\n생산 데이터를 분석하고 품질 이슈를 탐지합니다.\n자격요건\n제조 데이터...,주요업무\n생산 데이터를 분석하고 품질 이슈를 탐지합니다.\n자격요건\n제조 데이터...

In [8]:
# 특정 공고 1건을 세로로 길게 비교
if comparison_view.empty:
    print("comparison_view is empty")
else:
    target_offset = min(4, len(comparison_view))
    row = comparison_view.iloc[-target_offset]

    for col in comparison_view.columns:
        print(f"\n[{col}]")
        print(row[col])

[회사명_표시]
한국전자통신연구원

[공고제목_표시]
인공지능 리서처

[직무명_표시]
인공지능 리서처

[주요업무_표시]
차세대 인공지능 알고리즘을 연구합니다.

[주요업무_분석용]
차세대 인공지능 알고리즘을 연구합니다.

[주요업무_raw]
주요업무
차세대 인공지능 알고리즘을 연구합니다.
자격요건
연구 논문 작성 경험
실험 설계 역량
우대사항
국책과제 경험
핵심기술
딥러닝
실험설계

[자격요건_표시]
연구 논문 작성 경험
실험 설계 역량

[자격요건_분석용]
연구 논문 작성 경험
실험 설계 역량

[자격요건_raw]
연구 논문 작성 경험
실험 설계 역량

[우대사항_표시]
국책과제 경험

[우대사항_분석용]
국책과제 경험

[우대사항_raw]
국책과제 경험

[핵심기술_표시]
딥러닝
실험설계

[핵심기술_분석용]
딥러닝
실험설계

[핵심기술_raw]
딥러닝
실험설계

[상세본문_분석용]
주요업무
차세대 인공지능 알고리즘을 연구합니다.
자격요건
연구 논문 작성 경험
실험 설계 역량
우대사항
국책과제 경험
핵심기술
딥러닝
실험설계

[상세본문_raw]
주요업무
차세대 인공지능 알고리즘을 연구합니다.
자격요건
연구 논문 작성 경험
실험 설계 역량
우대사항
국책과제 경험
핵심기술
딥러닝
실험설계