# 0단계 소스 적격성 판정

공식성, 공개성, 구조 안정성을 기준으로 소스를 `approved`, `candidate`, `rejected`로 나눈다. 애매한 경우는 초반에 버리지 않고 `candidate`로 남겨 리콜을 확보한다.

In [1]:
from IPython.display import display
import pandas as pd

from jobs_market_v2.pipelines import discover_companies_pipeline, discover_sources_pipeline
from jobs_market_v2.settings import get_paths

paths = get_paths()
company_summary = discover_companies_pipeline()
source_summary = discover_sources_pipeline()
company_summary, source_summary

({'raw_candidate_count': 2590,
  'discovered_company_count': 2573,
  'non_company_removed_count': 17,
  'candidate_input_mode': 'source_backed_seed_records',
  'seeded_candidate_count': 2590,
  'tier_counts': {'중견/중소': 2007,
   '스타트업': 309,
   '공공·연구기관': 191,
   '대기업': 63,
   '외국계 한국법인': 2,
   '지역기업': 1}},
 {'approved_source_count': 428,
  'candidate_source_count': 174,
  'rejected_source_count': 2,
  'screened_source_count': 604,
  'company_input_count': 140,
  'company_input_mode': 'approved_companies'})

In [2]:
approved = pd.read_csv(paths.approved_sources_path)
candidate = pd.read_csv(paths.candidate_sources_path)
rejected = pd.read_csv(paths.rejected_sources_path)

display(approved.head())
display(candidate.head())
display(rejected.head())

,company_name,company_tier,source_name,source_url,source_type,source_bucket,source_domain,official_domain,official_domain_confidence,source_quality_score,is_official_hint,structure_hint,discovery_method,verification_status,failure_count,last_success_at,last_active_job_count,quarantine_reason,is_quarantined
0,마키나락스,중견/중소,마키나락스 공개 ATS,https://makinarocks.career.greetinghr.com,greetinghr,approved,makinarocks.career.greetinghr.com,makinarocks.ai,0.99,0.85,True,ats,homepage_link_probe,성공,0.0,2026-04-03T15:58:38+09:00,16.0,NaN,False
1,쿠팡,대기업,쿠팡 Greenhouse 공개 채용,https://boards-api.greenhouse.io/v1/boards/cou...,greenhouse,approved,boards-api.greenhouse.io,coupang.jobs,0.99,0.85,True,json,manual_seed_live,성공,0.0,2026-04-03T15:58:38+09:00,26.0,NaN,False
2,크래프톤,대기업,크래프톤 Greenhouse 공개 채용,https://boards-api.greenhouse.io/v1/boards/kra...,greenhouse,approved,boards-api.greenhouse.io,krafton.com,0.99,0.85,True,json,manual_seed_live,성공,0.0,2026-04-03T15:58:38+09:00,10.0,NaN,False
3,모빌린트,중견/중소,모빌린트 공식 채용,https://www.mobilint.com/careers,html_page,approved,www.mobilint.com,mobilint.com,0.99,0.75,True,html,homepage_link_probe,성공,0.0,2026-04-03T03:10:28+09:00,2.0,NaN,False
4,몰로코,외국계 한국법인,몰로코 Greenhouse 공개 채용,https://boards-api.greenhouse.io/v1/boards/mol...,greenhouse,approved,boards-api.greenhouse.io,moloco.com,0.99,0.85,True,json,manual_seed_live,성공,0.0,2026-04-03T15:58:38+09:00,8.0,NaN,False

,company_name,company_tier,source_name,source_url,source_type,source_bucket,source_domain,official_domain,official_domain_confidence,source_quality_score,is_official_hint,structure_hint,discovery_method,verification_status,failure_count,last_success_at,last_active_job_count,quarantine_reason,is_quarantined
0,안랩,중견/중소,안랩 공식 채용,https://www.ahnlab.com/ko/solution/threat-dete...,html_page,candidate,www.ahnlab.com,ahnlab.com,0.99,0.75,True,html,homepage_link_probe,성공,0.0,2026-04-03T03:10:28+09:00,2.0,NaN,False
1,안랩,중견/중소,안랩 공식 채용,https://www.ahnlab.com/ko/service/threat-actor...,html_page,candidate,www.ahnlab.com,ahnlab.com,0.99,0.75,True,html,homepage_link_probe,성공,0.0,2026-04-03T03:10:28+09:00,2.0,NaN,False
2,안랩,중견/중소,안랩 공식 채용,https://www.ahnlab.com/ko/product/threat-manag...,html_page,candidate,www.ahnlab.com,ahnlab.com,0.99,0.75,True,html,homepage_link_probe,성공,0.0,2026-04-03T03:10:28+09:00,2.0,NaN,False
3,비상교육,중견/중소,비상교육 공식 채용,https://career.visang.com,html_page,candidate,career.visang.com,visang.com,0.99,0.45,True,html,homepage_link_probe,성공,0.0,2026-04-03T03:03:57+09:00,2.0,NaN,False
4,바이트사이즈,중견/중소,바이트사이즈 공식 채용,https://career.thebytesize.ai/jobs,html_page,candidate,career.thebytesize.ai,thebytesize.ai,0.99,0.45,True,html,homepage_link_probe,성공,0.0,2026-04-03T03:03:57+09:00,1.0,NaN,False

,company_name,company_tier,source_name,source_url,source_type,source_bucket,source_domain,official_domain,official_domain_confidence,source_quality_score,is_official_hint,structure_hint,discovery_method,verification_status,failure_count,last_success_at,last_active_job_count,quarantine_reason,is_quarantined
0,원티드랩,중견/중소,원티드랩 공식 채용,https://www.wanted.co.kr/career_connect,html_page,rejected,www.wanted.co.kr,wanted.co.kr,0.99,0.75,True,html,homepage_link_probe,미검증,0.0,NaN,0.0,NaN,False
1,원티드랩,중견/중소,원티드랩 공식 채용,https://www.wanted.co.kr/wdlist,html_page,rejected,www.wanted.co.kr,wanted.co.kr,0.99,0.75,True,html,homepage_link_probe,미검증,0.0,NaN,0.0,NaN,False