# 1단계 1차 모집단 수집

`approved + candidate` 소스를 사용해 첫 공고 스냅샷을 수집하고 `staging`에 적재한다. 이 단계에서는 `master`를 갱신하지 않는다.

In [1]:
from IPython.display import display
import json
import pandas as pd

from jobs_market_v2.pipelines import build_coverage_report_pipeline
from jobs_market_v2.settings import get_paths

paths = get_paths()
smoke_summary = {
    "staging_exists": paths.staging_jobs_path.exists(),
    "raw_detail_exists": paths.raw_detail_path.exists(),
    "staging_path": str(paths.staging_jobs_path),
    "coverage_path": str(paths.coverage_report_path),
}
coverage_summary = build_coverage_report_pipeline()
smoke_summary, coverage_summary

({'staging_exists': True,
  'raw_detail_exists': True,
  'staging_path': '/Users/junheelee/Desktop/sctaper_p1/jobs_market_v2/runtime/staging_jobs.csv',
  'coverage_path': '/Users/junheelee/Desktop/sctaper_p1/jobs_market_v2/runtime/coverage_report.json'},
 {'발견 기업 수': 2573,
  '층별 발견 기업 수': {'대기업': 63,
   '스타트업': 309,
   '중견/중소': 2007,
   '공공·연구기관': 191,
   '외국계 한국법인': 2,
   '지역기업': 1},
  '공식 도메인 검증 성공 수': 2429,
  '층별 공식 도메인 검증 성공 수': {'대기업': 29,
   '스타트업': 36,
   '중견/중소': 436,
   '공공·연구기관': 66,
   '외국계 한국법인': 2,
   '지역기업': 1},
  '공식 채용 소스 검증 성공 수': 570,
  'discovery source 유형별 성공률': {'greenhouse': 0.8571,
   'greetinghr': 0.9333,
   'html_page': 0.9454,
   'lever': 1.0,
   'recruiter': 0.9444},
  '비기업 엔티티 제거 수': 17,
  'quarantine source 수': 0,
  '활성 공고 수': 193,
  '직무별 공고 수': {'데이터 분석가': 21,
   '데이터 사이언티스트': 12,
   '인공지능 리서처': 35,
   '인공지능 엔지니어': 125},
  '신규/유지/변경/미발견 수': {'신규': 11, '유지': 89, '변경': 3, '미발견': 2},
  'HHI': 0.0413,
  'top5 집중도': 0.3575})

In [2]:
staging = pd.read_csv(paths.staging_jobs_path)
display(staging.head())

print(paths.first_snapshot_path)
print(paths.coverage_report_path)
print(json.dumps(json.loads(paths.coverage_report_path.read_text(encoding='utf-8')), ensure_ascii=False, indent=2))

,job_key,change_hash,first_seen_at,last_seen_at,is_active,missing_count,snapshot_date,run_id,source_url,source_bucket,...,채용트랙_표시,채용트랙근거_표시,직무초점_표시,직무초점근거_표시,구분요약_표시,직무명_표시,주요업무_표시,자격요건_표시,우대사항_표시,핵심기술_표시
0,acdeca3194f547cfa91dce4b0228dcf48979618d1eaf14...,2698eafe9508c89e9ad72f969a0ccd3ac36c891a742c01...,2026-04-02T23:41:59+09:00,2026-04-03T15:58:38+09:00,True,0,2026-04-03,update-incremental-20260403205017179954-120d35f5,https://gazzi.ai/careers,approved,...,전문연구요원 / 석사,구조화 메타데이터 / 자격요건,검색 / LLM,주요업무,신입 / 전문연구요원 / 석사 / 검색 / LLM,인공지능 엔지니어,데이터/모델 최적화를 위한 이티엘 파이프라인 구축 및 모델 훈련/미세조정\n멀티모달...,대학원 석사 이상 학위 소지자 또는 졸업 예정자\n2026년 병역특례 전문연구요원 ...,"컴퓨터공학/인공지능 전공자 또는 유관 분야 실무 경험자\n에이전트 인공지능(랭체인,...",파이썬\n자바스크립트\n리눅스\n도커\n랭체인\n에이더블유에스
1,54239f62f548257f4700c0d0ba9515e8f4838f7f021654...,62c4ae9cfba3eea3c941035885a4d16ee108556d9f65c6...,2026-04-03T02:11:18+09:00,2026-04-03T02:11:18+09:00,True,0,2026-04-03,update-incremental-20260403205017179954-120d35f5,https://hugeailab.com/recruit,approved,...,일반채용,기본추론,최적화 / 제품분석,자격요건 / 주요업무,경력 3년+ / 최적화 / 제품분석,인공지능 엔지니어,외부 인공지능 모델 개발자와 협력하여 고성능 인공지능 모델을 개발하고 최적화합니다....,"인공지능/머신러닝 관련 분야에서 3년 이상의 경력이 필요합니다.\n파이썬, 텐서플로...","자연어 처리, 컴퓨터 비전, 추천 시스템 중 하나 이상의 전문 지식을 보유해야 합니...",파이썬\n텐서플로\n파이토치\n자연어 처리\n컴퓨터 비전\n추천 시스템\n에이더블유...
2,8c08ef4b136652711f3422ff39e2882374f32045ad131d...,4a731d89b2a3c7ed8e464aff62e2c8dcb8836c233a56f5...,2026-03-30T22:42:44+09:00,2026-04-03T20:50:17+09:00,True,0,2026-04-03,update-incremental-20260403205017179954-120d35f5,https://gowid.career.greetinghr.com,approved,...,일반채용,기본추론,시계열 / 제품분석,자격요건 / 주요업무,경력 / 시계열 / 제품분석,데이터 사이언티스트,"법인카드 이용 데이터, 재무 지표 등 다양한 금융 데이터를 기반으로\n안정성 평가,...",2년 이상의 데이터 사이언스 실무 경험 또는 이에 준하는 프로젝트/연구 경험이 있으...,금융 데이터 기반 시계열 예측 모델 개발 경험\n그래프 신경망(지엔엔) 모델링 및 ...,에스큐엘\n엠엘옵스
3,f2c4092751c810f49d2c315a4beb115280c7b061bb5d7b...,2cf3b6dd9f2b89eb834a8533300e00797df59090a8c43b...,2026-04-02T02:50:03+09:00,2026-04-02T02:50:03+09:00,True,0,2026-04-03,update-incremental-20260403205017179954-120d35f5,https://recruit.navercorp.com/rcrt/list.do,approved,...,박사 / 석사,우대사항,연구,제목/요건추론,경력 / 박사 / 석사,인공지능 리서처,대규모 실외 데이터를 기반으로 차세대 인공지능 기술을 연구 및 개발합니다.\n3 공...,"컴퓨터 비전, 3 비전, 딥러닝에 대한 전반적인 이해가 필요합니다.\n아래 분야 중...",관련 분야 석사/박사 학위 또는 이에 준하는 연구/개발 경험이 있는 분을 우대합니다...,컴퓨터 비전\n3 비전
4,2be64e75450abf6761094f0fb6011719890a6a9cd5f09d...,e58eba757b9580f991a8ad2ab3f02045965a0cb425a722...,2026-04-03T04:58:43+09:00,2026-04-03T15:58:38+09:00,True,0,2026-04-03,update-incremental-20260403205017179954-120d35f5,https://career.nota.ai/en/jobs,approved,...,전문연구요원,구조화 메타데이터,연구,제목/요건추론,전문연구요원,인공지능 리서처,"& 모든 포지션에서 전문연구요원, 산업기능요원으로 근무가 가능합니다. (단, 산업기...","채용 관련 문의사항은\n로 보내주세요.\n지원 전, 확인해주세요!\n제출하신 내용에...",별도 우대사항 미기재,NaN

/Users/junheelee/Desktop/sctaper_p1/jobs_market_v2/output_samples/first_snapshot_jobs.parquet
/Users/junheelee/Desktop/sctaper_p1/jobs_market_v2/runtime/coverage_report.json
{
  "발견 기업 수": 2573,
  "층별 발견 기업 수": {
    "대기업": 63,
    "스타트업": 309,
    "중견/중소": 2007,
    "공공·연구기관": 191,
    "외국계 한국법인": 2,
    "지역기업": 1
  },
  "공식 도메인 검증 성공 수": 2429,
  "층별 공식 도메인 검증 성공 수": {
    "대기업": 29,
    "스타트업": 36,
    "중견/중소": 436,
    "공공·연구기관": 66,
    "외국계 한국법인": 2,
    "지역기업": 1
  },
  "공식 채용 소스 검증 성공 수": 570,
  "discovery source 유형별 성공률": {
    "greenhouse": 0.8571,
    "greetinghr": 0.9333,
    "html_page": 0.9454,
    "lever": 1.0,
    "recruiter": 0.9444
  },
  "비기업 엔티티 제거 수": 17,
  "quarantine source 수": 0,
  "활성 공고 수": 193,
  "직무별 공고 수": {
    "데이터 분석가": 21,
    "데이터 사이언티스트": 12,
    "인공지능 리서처": 35,
    "인공지능 엔지니어": 125
  },
  "신규/유지/변경/미발견 수": {
    "신규": 11,
    "유지": 89,
    "변경": 3,
    "미발견": 2
  },
  "HHI": 0.0413,
  "top5 집중도": 0.3575
}

## 표시값, 분석용, 원문 비교 보기

`display`, `분석용`, `raw/detail` 기반 긴 텍스트를 같은 행에서 비교한다. 전처리 손실이 어느 단계에서 생겼는지 바로 확인할 수 있다.

In [3]:
import json
import pandas as pd
from IPython.display import display

from jobs_market_v2.html_utils import clean_html_text
from jobs_market_v2.settings import get_paths

paths = get_paths()
staging = pd.read_csv(paths.staging_jobs_path)
raw_detail = pd.read_json(paths.raw_detail_path, lines=True)


def pick(payload, *keys):
    if not isinstance(payload, dict):
        return ""
    for key in keys:
        value = payload.get(key, "")
        if value:
            return value
    return ""

raw_columns = ["job_key", "주요업무_raw", "자격요건_raw", "우대사항_raw", "핵심기술_raw", "상세본문_raw"]
if raw_detail.empty or "raw_payload_json" not in raw_detail.columns:
    compare_df = pd.DataFrame(columns=raw_columns)
else:
    raw_detail["raw_payload"] = raw_detail["raw_payload_json"].apply(json.loads)
    compare_df = raw_detail.copy()
    compare_df["주요업무_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "responsibilities", "main_tasks", "description_html", "description"))
    compare_df["자격요건_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "requirements", "description_html", "description"))
    compare_df["우대사항_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "preferred", "description_html", "description"))
    compare_df["핵심기술_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "core_skills", "skills", "description_html", "description"))
    compare_df["상세본문_raw"] = compare_df["raw_payload"].apply(lambda x: pick(x, "description_html", "description"))

    for col in ["주요업무_raw", "자격요건_raw", "우대사항_raw", "핵심기술_raw", "상세본문_raw"]:
        compare_df[col] = compare_df[col].fillna("").apply(clean_html_text)

comparison_view = staging.merge(
    compare_df[["job_key", "주요업무_raw", "자격요건_raw", "우대사항_raw", "핵심기술_raw", "상세본문_raw"]],
    on="job_key",
    how="left",
)

comparison_view = comparison_view[[
    "회사명_표시",
    "공고제목_표시",
    "직무명_표시",
    "주요업무_표시",
    "주요업무_분석용",
    "주요업무_raw",
    "자격요건_표시",
    "자격요건_분석용",
    "자격요건_raw",
    "우대사항_표시",
    "우대사항_분석용",
    "우대사항_raw",
    "핵심기술_표시",
    "핵심기술_분석용",
    "핵심기술_raw",
    "상세본문_분석용",
    "상세본문_raw",
]]

display(comparison_view.head(20))

,회사명_표시,공고제목_표시,직무명_표시,주요업무_표시,주요업무_분석용,주요업무_raw,자격요건_표시,자격요건_분석용,자격요건_raw,우대사항_표시,우대사항_분석용,우대사항_raw,핵심기술_표시,핵심기술_분석용,핵심기술_raw,상세본문_분석용,상세본문_raw
0,가치랩스,[병역특례 전문연구요원] AI 기술 및 응용솔루션 R&D 엔지니어 (1명),인공지능 엔지니어,데이터/모델 최적화를 위한 이티엘 파이프라인 구축 및 모델 훈련/미세조정\n멀티모달...,데이터/모델 최적화를 위한 이티엘 파이프라인 구축 및 모델 훈련/미세조정\n멀티모달...,NaN,대학원 석사 이상 학위 소지자 또는 졸업 예정자\n2026년 병역특례 전문연구요원 ...,대학원 석사 이상 학위 소지자 또는 졸업 예정자\n2026년 병역특례 전문연구요원 ...,NaN,"컴퓨터공학/인공지능 전공자 또는 유관 분야 실무 경험자\n에이전트 인공지능(랭체인,...","컴퓨터공학/인공지능 전공자 또는 유관 분야 실무 경험자\n에이전트 인공지능(랭체인,...",NaN,파이썬\n자바스크립트\n리눅스\n도커\n랭체인\n에이더블유에스,파이썬\n자바스크립트\n리눅스\n도커\n랭체인\n에이더블유에스,NaN,데이터/모델 최적화를 위한 이티엘 파이프라인 구축 및 모델 훈련/미세조정\n멀티모달...,NaN
1,거대한에이아이실험실 주식회사,AI 개발자(AI Model Developer/Researcher),인공지능 엔지니어,외부 인공지능 모델 개발자와 협력하여 고성능 인공지능 모델을 개발하고 최적화합니다....,외부 인공지능 모델 개발자와 협력하여 고성능 인공지능 모델을 개발하고 최적화합니다....,NaN,"인공지능/머신러닝 관련 분야에서 3년 이상의 경력이 필요합니다.\n파이썬, 텐서플로...","인공지능/머신러닝 관련 분야에서 3년 이상의 경력이 필요합니다.\n파이썬, 텐서플로...",NaN,"자연어 처리, 컴퓨터 비전, 추천 시스템 중 하나 이상의 전문 지식을 보유해야 합니...","자연어 처리, 컴퓨터 비전, 추천 시스템 중 하나 이상의 전문 지식을 보유해야 합니...",NaN,파이썬\n텐서플로\n파이토치\n자연어 처리\n컴퓨터 비전\n추천 시스템\n에이더블유...,파이썬\n텐서플로\n파이토치\n자연어 처리\n컴퓨터 비전\n추천 시스템\n에이더블유...,NaN,인공지능 개발자(인공지능 )\n담당 업무\n외부 인공지능 모델 개발자들과 협업하여 ...,NaN
2,고위드,[공통] Data Scientist,데이터 사이언티스트,"법인카드 이용 데이터, 재무 지표 등 다양한 금융 데이터를 기반으로\n안정성 평가,...","법인카드 이용 데이터, 재무 지표 등 다양한 금융 데이터를 기반으로\n안정성 평가,...","고위드 소개\n고위드는\n‘혁신성장기업에게 실시간 데이터를 기반으로, 최적의 타이밍...",2년 이상의 데이터 사이언스 실무 경험 또는 이에 준하는 프로젝트/연구 경험이 있으...,2년 이상의 데이터 사이언스 실무 경험 또는 이에 준하는 프로젝트/연구 경험이 있으...,"고위드 소개\n고위드는\n‘혁신성장기업에게 실시간 데이터를 기반으로, 최적의 타이밍...",금융 데이터 기반 시계열 예측 모델 개발 경험\n그래프 신경망(지엔엔) 모델링 및 ...,금융 데이터 기반 시계열 예측 모델 개발 경험\n그래프 신경망(지엔엔) 모델링 및 ...,"고위드 소개\n고위드는\n‘혁신성장기업에게 실시간 데이터를 기반으로, 최적의 타이밍...",에스큐엘\n엠엘옵스,에스큐엘\n엠엘옵스,"고위드 소개\n고위드는\n‘혁신성장기업에게 실시간 데이터를 기반으로, 최적의 타이밍...","법인카드 이용 데이터, 재무 지표 등 다양한 금융 데이터를 기반으로\n안정성 평가,...","고위드 소개\n고위드는\n‘혁신성장기업에게 실시간 데이터를 기반으로, 최적의 타이밍..."
3,네이버,[네이버랩스] Generative AI Research Engineer,인공지능 리서처,대규모 실외 데이터를 기반으로 차세대 인공지능 기술을 연구 및 개발합니다.\n3 공...,대규모 실외 데이터를 기반으로 차세대 인공지능 기술을 연구 및 개발합니다.\n3 공...,NaN,"컴퓨터 비전, 3 비전, 딥러닝에 대한 전반적인 이해가 필요합니다.\n아래 분야 중...","컴퓨터 비전, 3 비전, 딥러닝에 대한 전반적인 이해가 필요합니다.\n아래 분야 중...",NaN,관련 분야 석사/박사 학위 또는 이에 준하는 연구/개발 경험이 있는 분을 우대합니다...,관련 분야 석사/박사 학위 또는 이에 준하는 연구/개발 경험이 있는 분을 우대합니다...,NaN,컴퓨터 비전\n3 비전,컴퓨터 비전\n3 비전,NaN,"대규모 실외 데이터를 기반으로, 3 공간을 정밀하게 재현하는 수준을 넘어 현실 세계...",NaN
4,노타,전문연구요원 (R&D),인공지능 리서처,"& 모든 포지션에서 전문연구요원, 산업기능요원으로 근무가 가능합니다. (단, 산업기...","& 모든 포지션에서 전문연구요원, 산업기능요원으로 근무가 가능합니다. (단, 산업기...",NaN,"채용 관련 문의사항은\n로 보내주세요.\n지원 전, 확인해주세요!\n제출하신 내용에...","채용 관련 문의사항은\n로 보내주세요.\n지원 전, 확인해주세요!\n제출하신 내용에...",NaN,별도 우대사항 미기재,NaN,NaN,NaN,NaN,NaN,"채용 관련 문의사항은\n로 보내주세요.\n지원 전, 확인해주세요!\n제출하신 내용에...",NaN
5,노타,Talent Pool (R&D),인공지능 리서처,"& 모든 포지션에서 전문연구요원, 산업기능요원으로 근무가 가능합니다. (단, 산업기...","& 모든 포지션에서 전문연구요원, 산업기능요원으로 근무가 가능합니다. (단, 산업기...",NaN,을 통해 입사한 지원자에게는 내부 보상(현금성)이 제공될 예정입니다.\n채용 관련 ...,을 통해 입사한 지원자에게는 내부 보상(현금성)이 제공될 예정입니다.\n채용 관련 ...,NaN,별도 우대사항 미기재,NaN,NaN,컴퓨터비전,컴퓨터비전,NaN,을 통해 입사한 지원자에게는 내부 보상(현금성)이 제공될 예정입니다.\n채용 관련 ...,NaN
6,노타,[Solution AI-Industry] Business Developer,인공지능 엔지니어,산업안전 비전 인공지능/브이엘엠 솔루션 기반 신규 사업 기회를 발굴합니다.\n잠재 ...,산업안전 비전 인공지능/브이엘엠 솔루션 기반 신규 사업 기회를 발굴합니다.\n잠재 ...,NaN,논리적 사고로 복잡한 문제를 구조화하고 설득할 수 있는 역량을 보유해야 합니다.\n...,논리적 사고로 복잡한 문제를 구조화하고 설득할 수 있는 역량을 보유해야 합니다.\n...,NaN,"산업 안전, 보안 관제 분야 사업 경험이 있으면 좋습니다.\n비전 인공지능 또는 인...","산업 안전, 보안 관제 분야 사업 경험이 있으면 좋습니다.\n비전 인공지능 또는 인...",NaN,비전 인공지능\n인공지능 솔루션\n사업 개발\n사업 기회 발굴,비전 인공지능\n인공지능 솔루션\n사업 개발\n사업 기회 발굴,NaN,산업안전 비전 인공지능/브이엘엠 솔루션 기반 신규 사업 기회를 발굴합니다.\n잠재 ...,NaN
7,노타,[NetsPresso] Edge AI Engineer,인공지능 엔지니어,모델 변환 및 최적화 파이프라인을 구축하고 분석합니다.\n토치 모델을 오엔엔엑스로 ...,모델 변환 및 최적화 파이프라인을 구축하고 분석합니다.\n토치 모델을 오엔엔엑스로 ...,NaN,"오엔엔엑스 기반 모델 변환, 최적화, 디버깅 경험이 있어야 합니다.\n엔피유, 지피...","오엔엔엑스 기반 모델 변환, 최적화, 디버깅 경험이 있어야 합니다.\n엔피유, 지피...",NaN,다양한 벤더 컴파일러 사용 경험이 있으면 좋습니다.\n엠엘옵스 또는 엘엘엠 서빙 스...,다양한 벤더 컴파일러 사용 경험이 있으면 좋습니다.\n엠엘옵스 또는 엘엘엠 서빙 스...,NaN,트랜스포머\n디퓨전\n엠엘옵스\n엘엘엠,트랜스포머\n디퓨전\n엠엘옵스\n엘엘엠,NaN,모델 변환 및 최적화 파이프라인을 구축하고 분석합니다.\n토치 모델을 오엔엔엑스로 ...,NaN
8,노타,[NetsPresso] DevOps Engineer,인공지능 엔지니어,"씨아이씨디 파이프라인을 설계하고 자동화합니다.\n에스디케이/라이브러리 패키지 빌드,...","씨아이씨디 파이프라인을 설계하고 자동화합니다.\n에스디케이/라이브러리 패키지 빌드,...",NaN,데브옵스/인프라 엔지니어 경력 5년 이상이 필요합니다.\n에이더블유에스 클라우드 서...,데브옵스/인프라 엔지니어 경력 5년 이상이 필요합니다.\n에이더블유에스 클라우드 서...,NaN,엘엘엠옵스 또는 엠엘옵스 파이프라인 구축 및 운영 경험이 있으면 좋습니다.\n엘엘엠...,엘엘엠옵스 또는 엠엘옵스 파이프라인 구축 및 운영 경험이 있으면 좋습니다.\n엘엘엠...,NaN,쿠버네티스\n도커\n에이더블유에스\n리눅스\n테라폼\n앤서블\n프로메테우스\n그라파...,쿠버네티스\n도커\n에이더블유에스\n리눅스\n테라폼\n앤서블\n프로메테우스\n그라파...,NaN,"씨아이씨디 파이프라인을 설계하고 자동화합니다.\n에스디케이/라이브러리 패키지 빌드,...",NaN
9,노타,[NetsPresso] AI Platform Engineer,인공지능 엔지니어,초기 프로젝트의 기술 스택을 검토하고 도입합니다.\n비즈니스 요구사항과 고객 피드백...,초기 프로젝트의 기술 스택을 검토하고 도입합니다.\n비즈니스 요구사항과 고객 피드백...,NaN,"7년 이상의 백엔드 개발 경력 또는 그에 준하는 실력을 보유해야 합니다.\n파이썬,...","7년 이상의 백엔드 개발 경력 또는 그에 준하는 실력을 보유해야 합니다.\n파이썬,...",NaN,"쿠버네티스, 도커 기반 인프라 운영 경험이 있으면 좋습니다.\n엠엘옵스 파이프라인 ...","쿠버네티스, 도커 기반 인프라 운영 경험이 있으면 좋습니다.\n엠엘옵스 파이프라인 ...",NaN,파이썬\n자바\n도커\n쿠버네티스\n엠엘옵스\n텐서플로\n파이토치,파이썬\n자바\n도커\n쿠버네티스\n엠엘옵스\n텐서플로\n파이토치,NaN,초기 프로젝트의 기술 스택을 검토하고 도입합니다.\n비즈니스 요구사항과 고객 피드백...,NaN
10,노타,[NetsPresso] AI Compiler Engineer,인공지능 엔지니어,"중간 표현(엔피아이알)의 데이터 구조를 구현하고 기능을 확장합니다.\n파이토치, 오...","중간 표현(엔피아이알)의 데이터 구조를 구현하고 기능을 확장합니다.\n파이토치, 오...",NaN,"컴퓨터공학, 전자공학 등 관련 전공 학위를 소지해야 합니다.\n파이썬 언어에 능숙하...","컴퓨터공학, 전자공학 등 관련 전공 학위를 소지해야 합니다.\n파이썬 언어에 능숙하...",NaN,시스템 레벨 구현을 위한 역량 및 파이썬 활용 능력을 갖춘 분을 우대합니다.\n중앙...,시스템 레벨 구현을 위한 역량 및 파이썬 활용 능력을 갖춘 분을 우대합니다.\n중앙...,NaN,파이썬\n파이토치\n리눅스\n깃\n깃허브\n도커,파이썬\n파이토치\n리눅스\n깃\n깃허브\n도커,NaN,"중간 표현(엔피아이알)의 데이터 구조를 구현하고 기능을 확장합니다.\n파이토치, 오...",NaN
11,노타,[Solution] Global Software Engineer,인공지능 엔지니어,해외 고객 요구사항과 제품 간 차이를 메우기 위해 엠브이피를 신속하게 설계하고 구현...,해외 고객 요구사항과 제품 간 차이를 메우기 위해 엠브이피를 신속하게 설계하고 구현...,NaN,관련 분야 3년 이상의 경력과 해외 프로젝트 진행 경험이 필요합니다.\n해외 기술 ...,관련 분야 3년 이상의 경력과 해외 프로젝트 진행 경험이 필요합니다.\n해외 기술 ...,NaN,국내외 산업 현장에서 시스템 설치 및 운영 경험 또는 시스템 구축 관련 경력이 있으...,국내외 산업 현장에서 시스템 설치 및 운영 경험 또는 시스템 구축 관련 경력이 있으...,NaN,컴퓨터비전\n백엔드 개발\n프런트엔드 개발\n풀스택 개발\n깃허브,컴퓨터비전\n백엔드 개발\n프런트엔드 개발\n풀스택 개발\n깃허브,NaN,해외 고객 요구사항과 제품 간 차이를 메우기 위해 엠브이피를 신속하게 설계하고 구현...,NaN
12,노타,[NetsPresso] Edge AI Software Full Stack Engineer,인공지능 엔지니어,프론트엔드 및 백엔드 중심의 풀스택 개발을 담당합니다.\n엣지 인공지능 실험 및 개...,프론트엔드 및 백엔드 중심의 풀스택 개발을 담당합니다.\n엣지 인공지능 실험 및 개...,NaN,소프트웨어 개발 경력이 3년 이상이어야 합니다.\n프론트엔드 또는 백엔드 중 하나 ...,소프트웨어 개발 경력이 3년 이상이어야 합니다.\n프론트엔드 또는 백엔드 중 하나 ...,NaN,프론트엔드와 백엔드 모두 경험한 풀스택 개발자를 우대합니다.\n인공지능/머신러닝 파...,프론트엔드와 백엔드 모두 경험한 풀스택 개발자를 우대합니다.\n인공지능/머신러닝 파...,NaN,백엔드 시스템 및 인프라 설계\n파이썬 기반 백엔드 서비스 설계 및 구현\n모델 추...,백엔드 시스템 및 인프라 설계\n파이썬 기반 백엔드 서비스 설계 및 구현\n모델 추...,NaN,프론트엔드 및 백엔드 중심의 풀스택 개발을 담당합니다.\n엣지 인공지능 실험 및 개...,NaN
13,노타,[Solution] AI Software Engineer,인공지능 엔지니어,컴퓨터 비전 및 비전 언어 모델 기반의 인공지능 비전 솔루션을 설계하고 개발합니다....,컴퓨터 비전 및 비전 언어 모델 기반의 인공지능 비전 솔루션을 설계하고 개발합니다....,NaN,학위 취득 후 2년 이상 인공지능 비전 솔루션 개발 경력이 필요합니다.\n컴퓨터 과...,학위 취득 후 2년 이상 인공지능 비전 솔루션 개발 경력이 필요합니다.\n컴퓨터 과...,NaN,"자료구조, 알고리즘, 소프트웨어 설계 원리에 대한 탁월한 이해와 실전 적용 경험이 ...","자료구조, 알고리즘, 소프트웨어 설계 원리에 대한 탁월한 이해와 실전 적용 경험이 ...",NaN,파이썬\n파이토치\n도커\n쿠버네티스\n컴퓨터비전\n깃허브,파이썬\n파이토치\n도커\n쿠버네티스\n컴퓨터비전\n깃허브,NaN,컴퓨터 비전 및 비전 언어 모델 기반의 인공지능 비전 솔루션을 설계하고 개발합니다....,NaN
14,노타,[Solution AIE] AI Engineer,인공지능 엔지니어,브이엘엠 을 활용하여 새로운 도메인에 적용하고 성능을 검증합니다.\n멀티모달 데이터...,브이엘엠 을 활용하여 새로운 도메인에 적용하고 성능을 검증합니다.\n멀티모달 데이터...,NaN,"브이엘엠, 비전, 멀티모달 인공지능 등 관련 분야에서 5년 이상의 실무 또는 연구 ...","브이엘엠, 비전, 멀티모달 인공지능 등 관련 분야에서 5년 이상의 실무 또는 연구 ...",NaN,대표적인 브이엘엠 모델에 대한 이해 및 활용 경험이 있으면 좋습니다.\n컴퓨터 비전...,대표적인 브이엘엠 모델에 대한 이해 및 활용 경험이 있으면 좋습니다.\n컴퓨터 비전...,NaN,멀티모달\n컴퓨터비전\n파이토치\n텐서플로\n엠엘옵스,멀티모달\n컴퓨터비전\n파이토치\n텐서플로\n엠엘옵스,NaN,브이엘엠 을 활용하여 새로운 도메인에 적용하고 성능을 검증합니다.\n멀티모달 데이터...,NaN
15,다온에이치앤에스,[개발] Node.js 프로젝트 개발자 채용 (모집중),인공지능 엔지니어,를 활용한 개발을 담당합니다.\n등을 사용합니다.,를 활용한 개발을 담당합니다.\n등을 사용합니다.,채용공고\n[개발] Node.js 프로젝트 개발자 채용 (모집중)\n채용 포지션\n...,학력은 초대졸 이상이어야 합니다.\n신입 또는 2년 이상의 경력이 필요합니다.\n인...,학력은 초대졸 이상이어야 합니다.\n신입 또는 2년 이상의 경력이 필요합니다.\n인...,채용공고\n[개발] Node.js 프로젝트 개발자 채용 (모집중)\n채용 포지션\n...,정보처리기사 이상의 자격증을 보유한 분을 우대합니다.\n유관 업무 경력 2년 이상인...,정보처리기사 이상의 자격증을 보유한 분을 우대합니다.\n유관 업무 경력 2년 이상인...,채용공고\n[개발] Node.js 프로젝트 개발자 채용 (모집중)\n채용 포지션\n...,리눅스\n에이더블유에스\n클라우드,리눅스\n에이더블유에스\n클라우드,채용공고\n[개발] Node.js 프로젝트 개발자 채용 (모집중)\n채용 포지션\n...,채용공고\n[개발] 프로젝트 개발자 채용 (모집중)\n채용 포지션\n프로젝트 개발자...,채용공고\n[개발] Node.js 프로젝트 개발자 채용 (모집중)\n채용 포지션\n...
16,당근,Data Analyst,데이터 분석가,"데이터 분석 과제를 정의하고 제품 성장 및 사용자 경험 개선에 기여합니다.\n제품,...","데이터 분석 과제를 정의하고 제품 성장 및 사용자 경험 개선에 기여합니다.\n제품,...",당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,"웹/앱 데이터 분석 경험이 있으며, 이를 통해 제품을 개선해본 경험이 있는 분\n복...","웹/앱 데이터 분석 경험이 있으며, 이를 통해 제품을 개선해본 경험이 있는 분\n복...",당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,데이터를 활용하여 전략을 제시하고 비즈니스 성과를 창출한 경험이 있는 분\n분석을 ...,데이터를 활용하여 전략을 제시하고 비즈니스 성과를 창출한 경험이 있는 분\n분석을 ...,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,파이썬\n에스큐엘\n빅쿼리,파이썬\n에스큐엘\n빅쿼리,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,"데이터 분석 과제를 정의하고 제품 성장 및 사용자 경험 개선에 기여합니다.\n제품,...",당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...
17,당근,Data Analytics Engineer (인턴) | 로컬 비즈니스,데이터 분석가,구성원들이 신뢰하고 활용도 높게 사용할 수 있는 마트 데이터를 구축합니다.\n태블로...,구성원들이 신뢰하고 활용도 높게 사용할 수 있는 마트 데이터를 구축합니다.\n태블로...,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,"에스큐엘, 을 활용해 데이터를 분석하고 처리한 경험이 있는 분\n구성원 활용도가 높...","에스큐엘, 을 활용해 데이터를 분석하고 처리한 경험이 있는 분\n구성원 활용도가 높...",당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,이벤트 트래킹 설계나 로그 품질 보증 경험이 있는 분을 선호합니다.\n인공지능을 활...,이벤트 트래킹 설계나 로그 품질 보증 경험이 있는 분을 선호합니다.\n인공지능을 활...,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,태블로\n슈퍼셋\n에어플로우\n디비티\n지씨피\n에이더블유에스,태블로\n슈퍼셋\n에어플로우\n디비티\n지씨피\n에이더블유에스,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,구성원들이 신뢰하고 활용도 높게 사용할 수 있는 마트 데이터를 구축합니다.\n태블로...,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...
18,당근,Growth Manager (계약직) | 로컬 잡스,데이터 분석가,"유저 인터뷰, 데이터 분석 등을 통해 당근알바를 사용하는 여러 페르소나의 유저들을 ...","유저 인터뷰, 데이터 분석 등을 통해 당근알바를 사용하는 여러 페르소나의 유저들을 ...",당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,"3년 이하의 그로스, 씨알엠, 프로모션 기획/운영 경험이 있는 분\n주도적으로 업무...","3년 이하의 그로스, 씨알엠, 프로모션 기획/운영 경험이 있는 분\n주도적으로 업무...",당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,모바일 제품의 그로스 및 커뮤니티 제품에 대한 관심과 이해도가 높은 분\n프로젝트를...,모바일 제품의 그로스 및 커뮤니티 제품에 대한 관심과 이해도가 높은 분\n프로젝트를...,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,에스큐엘,에스큐엘,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,"유저 인터뷰, 데이터 분석 등을 통해 당근알바를 사용하는 여러 페르소나의 유저들을 ...",당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...
19,당근,Data Analytics Engineer | 테크코어 (데이터 가치화),데이터 분석가,전사 주요 데이터 마트( 등) 설계 및 운영을 주도합니다.\n전사 주요 지표를 정의...,전사 주요 데이터 마트( 등) 설계 및 운영을 주도합니다.\n전사 주요 지표를 정의...,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,"데이터 모델링/이티엘/데이터 마트 구축 경험이 있으신 분\n단일 모델 수준이 아닌,...","데이터 모델링/이티엘/데이터 마트 구축 경험이 있으신 분\n단일 모델 수준이 아닌,...",당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,전사 주요 지표를 정의 및 관리해 본 경험이 있는 분을 우대합니다.\n대규모 데이터...,전사 주요 지표를 정의 및 관리해 본 경험이 있는 분을 우대합니다.\n대규모 데이터...,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,에어플로우\n디비티\n에이비 테스트\n에이더블유에스\n지씨피\n데이터허브,에어플로우\n디비티\n에이비 테스트\n에이더블유에스\n지씨피\n데이터허브,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...,전사 주요 데이터 마트( 등) 설계 및 운영을 주도합니다.\n전사 주요 지표를 정의...,당근 팀 합류 여정에 오르신 것을 진심으로 환영해요\n당근은 회사의 성장에 맞춰 개...

In [4]:
# 특정 공고 1건을 세로로 길게 비교
if comparison_view.empty:
    print("comparison_view is empty")
else:
    target_offset = min(4, len(comparison_view))
    row = comparison_view.iloc[-target_offset]

    for col in comparison_view.columns:
        print(f"\n[{col}]")
        print(row[col])

[회사명_표시]
하이퍼커넥트

[공고제목_표시]
Senior Machine Learning Research Scientist (HYPERCONNECT AI)

[직무명_표시]
인공지능 리서처

[주요업무_표시]
제품의 문제를 연구 문제로 정의하고 해결합니다.
문제 정의, 가설 수립, 모델 선택 및 설계, 실험, 성과 분석까지 전 과정을 주도합니다.
연구 결과가 실제 제품 지표 개선으로 이어지는 것을 목표로 합니다.
하이퍼커넥트의 데이터와 제약 조건에 맞게 문제를 재정의합니다.
다양한 접근 방법과 기존 연구를 검토하여 상황에 맞는 해법을 선택하거나 새로 만듭니다.
반복적인 실험과 검증을 통해 제품에서 의미 있는 신호를 찾아냅니다.

[주요업무_분석용]
제품의 문제를 연구 문제로 정의하고 해결합니다.
문제 정의, 가설 수립, 모델 선택 및 설계, 실험, 성과 분석까지 전 과정을 주도합니다.
연구 결과가 실제 제품 지표 개선으로 이어지는 것을 목표로 합니다.
하이퍼커넥트의 데이터와 제약 조건에 맞게 문제를 재정의합니다.
다양한 접근 방법과 기존 연구를 검토하여 상황에 맞는 해법을 선택하거나 새로 만듭니다.
반복적인 실험과 검증을 통해 제품에서 의미 있는 신호를 찾아냅니다.

[주요업무_raw]
[HYPERCONNECT AI - AI Lab]
HYPERCONNECT AI는 머신러닝 연구를 통해 실제 비즈니스 성과를 만들어내는 조직입니다. 비즈니스 문제를 ML 문제로 재정의하고, 제품의 핵심 지표를 개선하는 데 집중합니다. 외부 솔루션을 단순히 적용하는 것은 지양하고, 문제 설정부터 다시 고민하며 최선의 선택을 직접 만들어갑니다. 그 결과 HYPERCONNECT AI의 연구 성과는 실제 비즈니스 임팩트로 이어져 왔으며, 그 중 아주 일부 사례는 본사인 Match Group의 Earnings Letter를 통해
소개
되기도 했습니다. HYPERCONNECT AI에서 연구는 목적이 아니라 수단이며, 목표는 명확한 비즈니스 임팩트입니다.
HYPERCONNECT AI에서 풀고 있는 문제들의 예시는 다음과 같습니다.
⬝
추천 모델 스케일링: LLM에서는 스케일링 법칙이 널리 받아들여지지만, 추천 모델에서는 그렇지 않습니다. 우리는 모델과 데이터 규모가 커질수록 성능도 함께 개선되는 구조를 만드는 연구를 진행합니다. LLM을 포함한 대형 모델을 다루되, 추론 등 현실적인 제약사항을 고려하여 모델을 설계합니다.
⬝
추천 모델 정렬: 모든 추천 문제는 결국 "이 유저에게 이 콘텐츠를 보여줬을 때 비즈니스가 얼마나 성장할지"를 정량적으로 측정하는 문제입니다. 강화학습, 인과 추론, 게임 이론 등을 바탕으로 스케일링된 추천 모델을 포스트 프로세싱하여 비즈니스 목표와 정렬하는 방법을 연구합니다.
⬝
멀티모달 LLM을 활용한 레이블링 기술 연구: 사람이 수행하는 이미지, 음성, 텍스트 레이블링을 멀티모달 LLM으로 대체하는 연구를 진행합니다. LLM의 회사 내부 데이터셋에 대한 이해도를 높이고, 회사의 레이블링 정책과 정렬된 레이블링 방법을 연구하는 등 다양한 연구를 통해 LLM의 레이블링 성능을 내부 직원 수준까지 끌어올리는 데 집중합니다.
연구 결과 중 의미 있는 성과는 논문이나 오픈소스 형태로 외부에 공개하기도 합니다. 논문 출판을 목표로 하지는 않지만, 제품 문제를 해결하는 과정에서 기존 연구로 충분히 설명되지 않는 부분이 있을 경우 이를 정리해 연구 성과로 남깁니다(
참고
). 지금까지 약 20여 건의 대외 연구 성과를 만들어 왔습니다.
AI로 비즈니스 문제를 해결하기 위해서는 모델 학습을 위한 인프라도 제대로 갖추어져야 합니다. HYPERCONNECT AI에서는 ML Research Scientist들이 충분히 모델 개발 및 실험을 진행할 수 있도록 자체적인 연구용 GPU 클러스터를 구축하여 활용하고 있습니다.
[ML Research Scientist 직무 소개]
HYPERCONNECT AI의 ML Research Scientist는 제품의 문제를 연구 문제로 바라보고 해결합니다. 문제 정의, 가설 수립, 모델 선택과 설계, 실험, 성과 분석까지 전 과정을 주도하며, 연구 결과가 실제 제품 지표 개선으로 이어지는 것을 목표로 합니다. 외부에서 이미 정의된 문제를 푸는 것이 아니라, HYPERCONNECT의 데이터와 제약 조건에 맞게 문제를 다시 정의합니다. 공개된 다양한 접근 방법과 기존 연구를 폭넓게 검토한 뒤, 상황에 맞는 해법을 선택하거나 새롭게 만들어냅니다. 반복적인 실험과 검증을 통해 제품에서 의미 있는 신호를 찾아내는 것이 이 역할의 핵심입니다(
참고).
연구 과정에서는 PM 및 소프트웨어 엔지니어 등 다양한 직군과 협업하지만, 연구 방향과 핵심 판단은 스스로 책임집니다. 단일 모델의 성능 개선을 넘어서, 시간이 지날수록 더 큰 임팩트를 낼 수 있는 구조를 만들어 가는 것을 중요하게 생각합니다. 데이터/백엔드 엔지니어링은 전담조직과 협업해 진행합니다.
제출해 주신 내용 중 허위 사실이 있거나 관련법 상 근로제공에 결격사유가 있는 경우 채용이 취소될 수 있으며, 필요시 사전에 안내된 채용 절차 외에도 추가 전형 및 서류 확인이 진행될 수 있습니다.
국가보훈대상자는 관계 법령에 따라 우대하오니, 해당되시는 분께서는 지원 시 고지해주시고 채용 시 증빙서류를 제출해주시기 바랍니다.
하이퍼커넥트가 채용하는 포지션에 지원하는 경우, 개인정보 처리에 관하여서는 본 개인정보처리방침이 적용됩니다:
https://career.hyperconnect.com/privacy
#HPCNT
Requirements
ML관련분야박사학위보유자또는석사학위보유자로서4년이상의관련분야연구경험을보유하신분복잡하고정답이정해지지않은비즈니스문제를ML문제로바꾸어풀수있는분강력한오너십으로연구전과정을주도적으로추진하실수있는분비즈니스임팩트를극대화하는방향으로연구마일스톤을설정하고전략적의사결정을하실수있는분여러직군의이해관계자와협업할수있는커뮤니케이션능력을갖추신분한개이상의ML도메인에대한깊이있는경험(arel
=
"noopenernoreferrer"class
=
"postings-link"href
=
"https:hyperconnect.github.io20241021beyond-collaborative-filtering.html"참고)과탄탄한MLfoundation을보유하신분성장에대한강한의지가있으시며,지속적으로성장한경험이있으신분한국어로원활한의사소통이가능하신분
Preferred Qualifications
AIML탑티어학회(NeurIPS,ICLR,ICML,CVPR,KDD등)에이론적인기여가포함된논문을게재한경험이있으신분연구팀혹은엔지니어링팀리드경험이있거나팀원들을성장시킨경험이있으신분(공동1저자또는교신저자경험포함)PMPO혹은그에준하는포지션으로유저경험을향상시켜본경험이있으신분인과관계분석및기타통계기법을사용하여데이터에서의미있는통찰력을발굴하고의사결정에올바르게적용하실수있는분클라이언트(Android,iOS),백엔드를포함해AIML분야외개발경험이풍부하신분이해관계자를설득할수있는비즈니스레벨의영어를구사하실수있는분
고용형태/채용절차
고용형태:정규직채용절차:서류전형&gt;코딩테스트&amp;과제전형&gt;1차면접&gt;2차면접&gt;3차면접(해당시)&gt;최종합격서류전형의경우합격자에한하여개별안내드릴예정입니다.지원서류:자유양식의상세경력기반영문이력서(PDF)

[자격요건_표시]
머신러닝 관련 분야 박사 학위 소지자 또는 석사 학위 소지자로서 4년 이상의 관련 분야 연구 경험이 있는 분
복잡하고 정답이 정해지지 않은 비즈니스 문제를 머신러닝 문제로 전환하여 해결할 수 있는 분
강력한 오너십을 가지고 연구 전 과정을 주도적으로 추진할 수 있는 분
비즈니스 임팩트를 극대화하는 방향으로 연구 마일스톤을 설정하고 전략적 의사결정을 할 수 있는 분
여러 직군의 이해관계자와 협업할 수 있는 의사소통 능력을 갖춘 분
한 개 이상의 머신러닝 도메인에 대한 깊이 있는 경험과 탄탄한 머신러닝 기반 지식을 보유한 분

[자격요건_분석용]
머신러닝 관련 분야 박사 학위 소지자 또는 석사 학위 소지자로서 4년 이상의 관련 분야 연구 경험이 있는 분
복잡하고 정답이 정해지지 않은 비즈니스 문제를 머신러닝 문제로 전환하여 해결할 수 있는 분
강력한 오너십을 가지고 연구 전 과정을 주도적으로 추진할 수 있는 분
비즈니스 임팩트를 극대화하는 방향으로 연구 마일스톤을 설정하고 전략적 의사결정을 할 수 있는 분
여러 직군의 이해관계자와 협업할 수 있는 의사소통 능력을 갖춘 분
한 개 이상의 머신러닝 도메인에 대한 깊이 있는 경험과 탄탄한 머신러닝 기반 지식을 보유한 분

[자격요건_raw]
[HYPERCONNECT AI - AI Lab]
HYPERCONNECT AI는 머신러닝 연구를 통해 실제 비즈니스 성과를 만들어내는 조직입니다. 비즈니스 문제를 ML 문제로 재정의하고, 제품의 핵심 지표를 개선하는 데 집중합니다. 외부 솔루션을 단순히 적용하는 것은 지양하고, 문제 설정부터 다시 고민하며 최선의 선택을 직접 만들어갑니다. 그 결과 HYPERCONNECT AI의 연구 성과는 실제 비즈니스 임팩트로 이어져 왔으며, 그 중 아주 일부 사례는 본사인 Match Group의 Earnings Letter를 통해
소개
되기도 했습니다. HYPERCONNECT AI에서 연구는 목적이 아니라 수단이며, 목표는 명확한 비즈니스 임팩트입니다.
HYPERCONNECT AI에서 풀고 있는 문제들의 예시는 다음과 같습니다.
⬝
추천 모델 스케일링: LLM에서는 스케일링 법칙이 널리 받아들여지지만, 추천 모델에서는 그렇지 않습니다. 우리는 모델과 데이터 규모가 커질수록 성능도 함께 개선되는 구조를 만드는 연구를 진행합니다. LLM을 포함한 대형 모델을 다루되, 추론 등 현실적인 제약사항을 고려하여 모델을 설계합니다.
⬝
추천 모델 정렬: 모든 추천 문제는 결국 "이 유저에게 이 콘텐츠를 보여줬을 때 비즈니스가 얼마나 성장할지"를 정량적으로 측정하는 문제입니다. 강화학습, 인과 추론, 게임 이론 등을 바탕으로 스케일링된 추천 모델을 포스트 프로세싱하여 비즈니스 목표와 정렬하는 방법을 연구합니다.
⬝
멀티모달 LLM을 활용한 레이블링 기술 연구: 사람이 수행하는 이미지, 음성, 텍스트 레이블링을 멀티모달 LLM으로 대체하는 연구를 진행합니다. LLM의 회사 내부 데이터셋에 대한 이해도를 높이고, 회사의 레이블링 정책과 정렬된 레이블링 방법을 연구하는 등 다양한 연구를 통해 LLM의 레이블링 성능을 내부 직원 수준까지 끌어올리는 데 집중합니다.
연구 결과 중 의미 있는 성과는 논문이나 오픈소스 형태로 외부에 공개하기도 합니다. 논문 출판을 목표로 하지는 않지만, 제품 문제를 해결하는 과정에서 기존 연구로 충분히 설명되지 않는 부분이 있을 경우 이를 정리해 연구 성과로 남깁니다(
참고
). 지금까지 약 20여 건의 대외 연구 성과를 만들어 왔습니다.
AI로 비즈니스 문제를 해결하기 위해서는 모델 학습을 위한 인프라도 제대로 갖추어져야 합니다. HYPERCONNECT AI에서는 ML Research Scientist들이 충분히 모델 개발 및 실험을 진행할 수 있도록 자체적인 연구용 GPU 클러스터를 구축하여 활용하고 있습니다.
[ML Research Scientist 직무 소개]
HYPERCONNECT AI의 ML Research Scientist는 제품의 문제를 연구 문제로 바라보고 해결합니다. 문제 정의, 가설 수립, 모델 선택과 설계, 실험, 성과 분석까지 전 과정을 주도하며, 연구 결과가 실제 제품 지표 개선으로 이어지는 것을 목표로 합니다. 외부에서 이미 정의된 문제를 푸는 것이 아니라, HYPERCONNECT의 데이터와 제약 조건에 맞게 문제를 다시 정의합니다. 공개된 다양한 접근 방법과 기존 연구를 폭넓게 검토한 뒤, 상황에 맞는 해법을 선택하거나 새롭게 만들어냅니다. 반복적인 실험과 검증을 통해 제품에서 의미 있는 신호를 찾아내는 것이 이 역할의 핵심입니다(
참고).
연구 과정에서는 PM 및 소프트웨어 엔지니어 등 다양한 직군과 협업하지만, 연구 방향과 핵심 판단은 스스로 책임집니다. 단일 모델의 성능 개선을 넘어서, 시간이 지날수록 더 큰 임팩트를 낼 수 있는 구조를 만들어 가는 것을 중요하게 생각합니다. 데이터/백엔드 엔지니어링은 전담조직과 협업해 진행합니다.
제출해 주신 내용 중 허위 사실이 있거나 관련법 상 근로제공에 결격사유가 있는 경우 채용이 취소될 수 있으며, 필요시 사전에 안내된 채용 절차 외에도 추가 전형 및 서류 확인이 진행될 수 있습니다.
국가보훈대상자는 관계 법령에 따라 우대하오니, 해당되시는 분께서는 지원 시 고지해주시고 채용 시 증빙서류를 제출해주시기 바랍니다.
하이퍼커넥트가 채용하는 포지션에 지원하는 경우, 개인정보 처리에 관하여서는 본 개인정보처리방침이 적용됩니다:
https://career.hyperconnect.com/privacy
#HPCNT
Requirements
ML관련분야박사학위보유자또는석사학위보유자로서4년이상의관련분야연구경험을보유하신분복잡하고정답이정해지지않은비즈니스문제를ML문제로바꾸어풀수있는분강력한오너십으로연구전과정을주도적으로추진하실수있는분비즈니스임팩트를극대화하는방향으로연구마일스톤을설정하고전략적의사결정을하실수있는분여러직군의이해관계자와협업할수있는커뮤니케이션능력을갖추신분한개이상의ML도메인에대한깊이있는경험(arel
=
"noopenernoreferrer"class
=
"postings-link"href
=
"https:hyperconnect.github.io20241021beyond-collaborative-filtering.html"참고)과탄탄한MLfoundation을보유하신분성장에대한강한의지가있으시며,지속적으로성장한경험이있으신분한국어로원활한의사소통이가능하신분
Preferred Qualifications
AIML탑티어학회(NeurIPS,ICLR,ICML,CVPR,KDD등)에이론적인기여가포함된논문을게재한경험이있으신분연구팀혹은엔지니어링팀리드경험이있거나팀원들을성장시킨경험이있으신분(공동1저자또는교신저자경험포함)PMPO혹은그에준하는포지션으로유저경험을향상시켜본경험이있으신분인과관계분석및기타통계기법을사용하여데이터에서의미있는통찰력을발굴하고의사결정에올바르게적용하실수있는분클라이언트(Android,iOS),백엔드를포함해AIML분야외개발경험이풍부하신분이해관계자를설득할수있는비즈니스레벨의영어를구사하실수있는분
고용형태/채용절차
고용형태:정규직채용절차:서류전형&gt;코딩테스트&amp;과제전형&gt;1차면접&gt;2차면접&gt;3차면접(해당시)&gt;최종합격서류전형의경우합격자에한하여개별안내드릴예정입니다.지원서류:자유양식의상세경력기반영문이력서(PDF)

[우대사항_표시]
인공지능/머신러닝 탑티어 학회(뉴립스, 아이씨엘알, 아이씨엠엘, 씨브이피알, 케이디디 등)에 이론적인 기여가 포함된 논문을 게재한 경험이 있는 분
연구팀 또는 엔지니어링팀 리드 경험이 있거나 팀원들을 성장시킨 경험이 있는 분
피엠/피오 또는 그에 준하는 포지션으로 사용자 경험을 향상시켜본 경험이 있는 분
인과관계 분석 및 기타 통계 기법을 사용하여 데이터에서 의미 있는 통찰력을 발굴하고 의사결정에 올바르게 적용할 수 있는 분
클라이언트(안드로이드, 아이오에스), 백엔드를 포함해 인공지능/머신러닝 분야 외 개발 경험이 풍부하신 분
이해관계자를 설득할 수 있는 비즈니스 수준의 영어를 구사할 수 있는 분

[우대사항_분석용]
인공지능/머신러닝 탑티어 학회(뉴립스, 아이씨엘알, 아이씨엠엘, 씨브이피알, 케이디디 등)에 이론적인 기여가 포함된 논문을 게재한 경험이 있는 분
연구팀 또는 엔지니어링팀 리드 경험이 있거나 팀원들을 성장시킨 경험이 있는 분
피엠/피오 또는 그에 준하는 포지션으로 사용자 경험을 향상시켜본 경험이 있는 분
인과관계 분석 및 기타 통계 기법을 사용하여 데이터에서 의미 있는 통찰력을 발굴하고 의사결정에 올바르게 적용할 수 있는 분
클라이언트(안드로이드, 아이오에스), 백엔드를 포함해 인공지능/머신러닝 분야 외 개발 경험이 풍부하신 분
이해관계자를 설득할 수 있는 비즈니스 수준의 영어를 구사할 수 있는 분

[우대사항_raw]
[HYPERCONNECT AI - AI Lab]
HYPERCONNECT AI는 머신러닝 연구를 통해 실제 비즈니스 성과를 만들어내는 조직입니다. 비즈니스 문제를 ML 문제로 재정의하고, 제품의 핵심 지표를 개선하는 데 집중합니다. 외부 솔루션을 단순히 적용하는 것은 지양하고, 문제 설정부터 다시 고민하며 최선의 선택을 직접 만들어갑니다. 그 결과 HYPERCONNECT AI의 연구 성과는 실제 비즈니스 임팩트로 이어져 왔으며, 그 중 아주 일부 사례는 본사인 Match Group의 Earnings Letter를 통해
소개
되기도 했습니다. HYPERCONNECT AI에서 연구는 목적이 아니라 수단이며, 목표는 명확한 비즈니스 임팩트입니다.
HYPERCONNECT AI에서 풀고 있는 문제들의 예시는 다음과 같습니다.
⬝
추천 모델 스케일링: LLM에서는 스케일링 법칙이 널리 받아들여지지만, 추천 모델에서는 그렇지 않습니다. 우리는 모델과 데이터 규모가 커질수록 성능도 함께 개선되는 구조를 만드는 연구를 진행합니다. LLM을 포함한 대형 모델을 다루되, 추론 등 현실적인 제약사항을 고려하여 모델을 설계합니다.
⬝
추천 모델 정렬: 모든 추천 문제는 결국 "이 유저에게 이 콘텐츠를 보여줬을 때 비즈니스가 얼마나 성장할지"를 정량적으로 측정하는 문제입니다. 강화학습, 인과 추론, 게임 이론 등을 바탕으로 스케일링된 추천 모델을 포스트 프로세싱하여 비즈니스 목표와 정렬하는 방법을 연구합니다.
⬝
멀티모달 LLM을 활용한 레이블링 기술 연구: 사람이 수행하는 이미지, 음성, 텍스트 레이블링을 멀티모달 LLM으로 대체하는 연구를 진행합니다. LLM의 회사 내부 데이터셋에 대한 이해도를 높이고, 회사의 레이블링 정책과 정렬된 레이블링 방법을 연구하는 등 다양한 연구를 통해 LLM의 레이블링 성능을 내부 직원 수준까지 끌어올리는 데 집중합니다.
연구 결과 중 의미 있는 성과는 논문이나 오픈소스 형태로 외부에 공개하기도 합니다. 논문 출판을 목표로 하지는 않지만, 제품 문제를 해결하는 과정에서 기존 연구로 충분히 설명되지 않는 부분이 있을 경우 이를 정리해 연구 성과로 남깁니다(
참고
). 지금까지 약 20여 건의 대외 연구 성과를 만들어 왔습니다.
AI로 비즈니스 문제를 해결하기 위해서는 모델 학습을 위한 인프라도 제대로 갖추어져야 합니다. HYPERCONNECT AI에서는 ML Research Scientist들이 충분히 모델 개발 및 실험을 진행할 수 있도록 자체적인 연구용 GPU 클러스터를 구축하여 활용하고 있습니다.
[ML Research Scientist 직무 소개]
HYPERCONNECT AI의 ML Research Scientist는 제품의 문제를 연구 문제로 바라보고 해결합니다. 문제 정의, 가설 수립, 모델 선택과 설계, 실험, 성과 분석까지 전 과정을 주도하며, 연구 결과가 실제 제품 지표 개선으로 이어지는 것을 목표로 합니다. 외부에서 이미 정의된 문제를 푸는 것이 아니라, HYPERCONNECT의 데이터와 제약 조건에 맞게 문제를 다시 정의합니다. 공개된 다양한 접근 방법과 기존 연구를 폭넓게 검토한 뒤, 상황에 맞는 해법을 선택하거나 새롭게 만들어냅니다. 반복적인 실험과 검증을 통해 제품에서 의미 있는 신호를 찾아내는 것이 이 역할의 핵심입니다(
참고).
연구 과정에서는 PM 및 소프트웨어 엔지니어 등 다양한 직군과 협업하지만, 연구 방향과 핵심 판단은 스스로 책임집니다. 단일 모델의 성능 개선을 넘어서, 시간이 지날수록 더 큰 임팩트를 낼 수 있는 구조를 만들어 가는 것을 중요하게 생각합니다. 데이터/백엔드 엔지니어링은 전담조직과 협업해 진행합니다.
제출해 주신 내용 중 허위 사실이 있거나 관련법 상 근로제공에 결격사유가 있는 경우 채용이 취소될 수 있으며, 필요시 사전에 안내된 채용 절차 외에도 추가 전형 및 서류 확인이 진행될 수 있습니다.
국가보훈대상자는 관계 법령에 따라 우대하오니, 해당되시는 분께서는 지원 시 고지해주시고 채용 시 증빙서류를 제출해주시기 바랍니다.
하이퍼커넥트가 채용하는 포지션에 지원하는 경우, 개인정보 처리에 관하여서는 본 개인정보처리방침이 적용됩니다:
https://career.hyperconnect.com/privacy
#HPCNT
Requirements
ML관련분야박사학위보유자또는석사학위보유자로서4년이상의관련분야연구경험을보유하신분복잡하고정답이정해지지않은비즈니스문제를ML문제로바꾸어풀수있는분강력한오너십으로연구전과정을주도적으로추진하실수있는분비즈니스임팩트를극대화하는방향으로연구마일스톤을설정하고전략적의사결정을하실수있는분여러직군의이해관계자와협업할수있는커뮤니케이션능력을갖추신분한개이상의ML도메인에대한깊이있는경험(arel
=
"noopenernoreferrer"class
=
"postings-link"href
=
"https:hyperconnect.github.io20241021beyond-collaborative-filtering.html"참고)과탄탄한MLfoundation을보유하신분성장에대한강한의지가있으시며,지속적으로성장한경험이있으신분한국어로원활한의사소통이가능하신분
Preferred Qualifications
AIML탑티어학회(NeurIPS,ICLR,ICML,CVPR,KDD등)에이론적인기여가포함된논문을게재한경험이있으신분연구팀혹은엔지니어링팀리드경험이있거나팀원들을성장시킨경험이있으신분(공동1저자또는교신저자경험포함)PMPO혹은그에준하는포지션으로유저경험을향상시켜본경험이있으신분인과관계분석및기타통계기법을사용하여데이터에서의미있는통찰력을발굴하고의사결정에올바르게적용하실수있는분클라이언트(Android,iOS),백엔드를포함해AIML분야외개발경험이풍부하신분이해관계자를설득할수있는비즈니스레벨의영어를구사하실수있는분
고용형태/채용절차
고용형태:정규직채용절차:서류전형&gt;코딩테스트&amp;과제전형&gt;1차면접&gt;2차면접&gt;3차면접(해당시)&gt;최종합격서류전형의경우합격자에한하여개별안내드릴예정입니다.지원서류:자유양식의상세경력기반영문이력서(PDF)

[핵심기술_표시]
데이터 분석
통계

[핵심기술_분석용]
데이터 분석
통계

[핵심기술_raw]
[HYPERCONNECT AI - AI Lab]
HYPERCONNECT AI는 머신러닝 연구를 통해 실제 비즈니스 성과를 만들어내는 조직입니다. 비즈니스 문제를 ML 문제로 재정의하고, 제품의 핵심 지표를 개선하는 데 집중합니다. 외부 솔루션을 단순히 적용하는 것은 지양하고, 문제 설정부터 다시 고민하며 최선의 선택을 직접 만들어갑니다. 그 결과 HYPERCONNECT AI의 연구 성과는 실제 비즈니스 임팩트로 이어져 왔으며, 그 중 아주 일부 사례는 본사인 Match Group의 Earnings Letter를 통해
소개
되기도 했습니다. HYPERCONNECT AI에서 연구는 목적이 아니라 수단이며, 목표는 명확한 비즈니스 임팩트입니다.
HYPERCONNECT AI에서 풀고 있는 문제들의 예시는 다음과 같습니다.
⬝
추천 모델 스케일링: LLM에서는 스케일링 법칙이 널리 받아들여지지만, 추천 모델에서는 그렇지 않습니다. 우리는 모델과 데이터 규모가 커질수록 성능도 함께 개선되는 구조를 만드는 연구를 진행합니다. LLM을 포함한 대형 모델을 다루되, 추론 등 현실적인 제약사항을 고려하여 모델을 설계합니다.
⬝
추천 모델 정렬: 모든 추천 문제는 결국 "이 유저에게 이 콘텐츠를 보여줬을 때 비즈니스가 얼마나 성장할지"를 정량적으로 측정하는 문제입니다. 강화학습, 인과 추론, 게임 이론 등을 바탕으로 스케일링된 추천 모델을 포스트 프로세싱하여 비즈니스 목표와 정렬하는 방법을 연구합니다.
⬝
멀티모달 LLM을 활용한 레이블링 기술 연구: 사람이 수행하는 이미지, 음성, 텍스트 레이블링을 멀티모달 LLM으로 대체하는 연구를 진행합니다. LLM의 회사 내부 데이터셋에 대한 이해도를 높이고, 회사의 레이블링 정책과 정렬된 레이블링 방법을 연구하는 등 다양한 연구를 통해 LLM의 레이블링 성능을 내부 직원 수준까지 끌어올리는 데 집중합니다.
연구 결과 중 의미 있는 성과는 논문이나 오픈소스 형태로 외부에 공개하기도 합니다. 논문 출판을 목표로 하지는 않지만, 제품 문제를 해결하는 과정에서 기존 연구로 충분히 설명되지 않는 부분이 있을 경우 이를 정리해 연구 성과로 남깁니다(
참고
). 지금까지 약 20여 건의 대외 연구 성과를 만들어 왔습니다.
AI로 비즈니스 문제를 해결하기 위해서는 모델 학습을 위한 인프라도 제대로 갖추어져야 합니다. HYPERCONNECT AI에서는 ML Research Scientist들이 충분히 모델 개발 및 실험을 진행할 수 있도록 자체적인 연구용 GPU 클러스터를 구축하여 활용하고 있습니다.
[ML Research Scientist 직무 소개]
HYPERCONNECT AI의 ML Research Scientist는 제품의 문제를 연구 문제로 바라보고 해결합니다. 문제 정의, 가설 수립, 모델 선택과 설계, 실험, 성과 분석까지 전 과정을 주도하며, 연구 결과가 실제 제품 지표 개선으로 이어지는 것을 목표로 합니다. 외부에서 이미 정의된 문제를 푸는 것이 아니라, HYPERCONNECT의 데이터와 제약 조건에 맞게 문제를 다시 정의합니다. 공개된 다양한 접근 방법과 기존 연구를 폭넓게 검토한 뒤, 상황에 맞는 해법을 선택하거나 새롭게 만들어냅니다. 반복적인 실험과 검증을 통해 제품에서 의미 있는 신호를 찾아내는 것이 이 역할의 핵심입니다(
참고).
연구 과정에서는 PM 및 소프트웨어 엔지니어 등 다양한 직군과 협업하지만, 연구 방향과 핵심 판단은 스스로 책임집니다. 단일 모델의 성능 개선을 넘어서, 시간이 지날수록 더 큰 임팩트를 낼 수 있는 구조를 만들어 가는 것을 중요하게 생각합니다. 데이터/백엔드 엔지니어링은 전담조직과 협업해 진행합니다.
제출해 주신 내용 중 허위 사실이 있거나 관련법 상 근로제공에 결격사유가 있는 경우 채용이 취소될 수 있으며, 필요시 사전에 안내된 채용 절차 외에도 추가 전형 및 서류 확인이 진행될 수 있습니다.
국가보훈대상자는 관계 법령에 따라 우대하오니, 해당되시는 분께서는 지원 시 고지해주시고 채용 시 증빙서류를 제출해주시기 바랍니다.
하이퍼커넥트가 채용하는 포지션에 지원하는 경우, 개인정보 처리에 관하여서는 본 개인정보처리방침이 적용됩니다:
https://career.hyperconnect.com/privacy
#HPCNT
Requirements
ML관련분야박사학위보유자또는석사학위보유자로서4년이상의관련분야연구경험을보유하신분복잡하고정답이정해지지않은비즈니스문제를ML문제로바꾸어풀수있는분강력한오너십으로연구전과정을주도적으로추진하실수있는분비즈니스임팩트를극대화하는방향으로연구마일스톤을설정하고전략적의사결정을하실수있는분여러직군의이해관계자와협업할수있는커뮤니케이션능력을갖추신분한개이상의ML도메인에대한깊이있는경험(arel
=
"noopenernoreferrer"class
=
"postings-link"href
=
"https:hyperconnect.github.io20241021beyond-collaborative-filtering.html"참고)과탄탄한MLfoundation을보유하신분성장에대한강한의지가있으시며,지속적으로성장한경험이있으신분한국어로원활한의사소통이가능하신분
Preferred Qualifications
AIML탑티어학회(NeurIPS,ICLR,ICML,CVPR,KDD등)에이론적인기여가포함된논문을게재한경험이있으신분연구팀혹은엔지니어링팀리드경험이있거나팀원들을성장시킨경험이있으신분(공동1저자또는교신저자경험포함)PMPO혹은그에준하는포지션으로유저경험을향상시켜본경험이있으신분인과관계분석및기타통계기법을사용하여데이터에서의미있는통찰력을발굴하고의사결정에올바르게적용하실수있는분클라이언트(Android,iOS),백엔드를포함해AIML분야외개발경험이풍부하신분이해관계자를설득할수있는비즈니스레벨의영어를구사하실수있는분
고용형태/채용절차
고용형태:정규직채용절차:서류전형&gt;코딩테스트&amp;과제전형&gt;1차면접&gt;2차면접&gt;3차면접(해당시)&gt;최종합격서류전형의경우합격자에한하여개별안내드릴예정입니다.지원서류:자유양식의상세경력기반영문이력서(PDF)

[상세본문_분석용]
제품의 문제를 연구 문제로 정의하고 해결합니다.
문제 정의, 가설 수립, 모델 선택 및 설계, 실험, 성과 분석까지 전 과정을 주도합니다.
연구 결과가 실제 제품 지표 개선으로 이어지는 것을 목표로 합니다.
하이퍼커넥트의 데이터와 제약 조건에 맞게 문제를 재정의합니다.
다양한 접근 방법과 기존 연구를 검토하여 상황에 맞는 해법을 선택하거나 새로 만듭니다.
반복적인 실험과 검증을 통해 제품에서 의미 있는 신호를 찾아냅니다.
머신러닝 관련 분야 박사 학위 소지자 또는 석사 학위 소지자로서 4년 이상의 관련 분야 연구 경험이 있는 분
복잡하고 정답이 정해지지 않은 비즈니스 문제를 머신러닝 문제로 전환하여 해결할 수 있는 분
강력한 오너십을 가지고 연구 전 과정을 주도적으로 추진할 수 있는 분
비즈니스 임팩트를 극대화하는 방향으로 연구 마일스톤을 설정하고 전략적 의사결정을 할 수 있는 분
여러 직군의 이해관계자와 협업할 수 있는 의사소통 능력을 갖춘 분
한 개 이상의 머신러닝 도메인에 대한 깊이 있는 경험과 탄탄한 머신러닝 기반 지식을 보유한 분
인공지능/머신러닝 탑티어 학회(뉴립스, 아이씨엘알, 아이씨엠엘, 씨브이피알, 케이디디 등)에 이론적인 기여가 포함된 논문을 게재한 경험이 있는 분
연구팀 또는 엔지니어링팀 리드 경험이 있거나 팀원들을 성장시킨 경험이 있는 분
피엠/피오 또는 그에 준하는 포지션으로 사용자 경험을 향상시켜본 경험이 있는 분
인과관계 분석 및 기타 통계 기법을 사용하여 데이터에서 의미 있는 통찰력을 발굴하고 의사결정에 올바르게 적용할 수 있는 분
클라이언트(안드로이드, 아이오에스), 백엔드를 포함해 인공지능/머신러닝 분야 외 개발 경험이 풍부하신 분
이해관계자를 설득할 수 있는 비즈니스 수준의 영어를 구사할 수 있는 분

[상세본문_raw]
[HYPERCONNECT AI - AI Lab]
HYPERCONNECT AI는 머신러닝 연구를 통해 실제 비즈니스 성과를 만들어내는 조직입니다. 비즈니스 문제를 ML 문제로 재정의하고, 제품의 핵심 지표를 개선하는 데 집중합니다. 외부 솔루션을 단순히 적용하는 것은 지양하고, 문제 설정부터 다시 고민하며 최선의 선택을 직접 만들어갑니다. 그 결과 HYPERCONNECT AI의 연구 성과는 실제 비즈니스 임팩트로 이어져 왔으며, 그 중 아주 일부 사례는 본사인 Match Group의 Earnings Letter를 통해
소개
되기도 했습니다. HYPERCONNECT AI에서 연구는 목적이 아니라 수단이며, 목표는 명확한 비즈니스 임팩트입니다.
HYPERCONNECT AI에서 풀고 있는 문제들의 예시는 다음과 같습니다.
⬝
추천 모델 스케일링: LLM에서는 스케일링 법칙이 널리 받아들여지지만, 추천 모델에서는 그렇지 않습니다. 우리는 모델과 데이터 규모가 커질수록 성능도 함께 개선되는 구조를 만드는 연구를 진행합니다. LLM을 포함한 대형 모델을 다루되, 추론 등 현실적인 제약사항을 고려하여 모델을 설계합니다.
⬝
추천 모델 정렬: 모든 추천 문제는 결국 "이 유저에게 이 콘텐츠를 보여줬을 때 비즈니스가 얼마나 성장할지"를 정량적으로 측정하는 문제입니다. 강화학습, 인과 추론, 게임 이론 등을 바탕으로 스케일링된 추천 모델을 포스트 프로세싱하여 비즈니스 목표와 정렬하는 방법을 연구합니다.
⬝
멀티모달 LLM을 활용한 레이블링 기술 연구: 사람이 수행하는 이미지, 음성, 텍스트 레이블링을 멀티모달 LLM으로 대체하는 연구를 진행합니다. LLM의 회사 내부 데이터셋에 대한 이해도를 높이고, 회사의 레이블링 정책과 정렬된 레이블링 방법을 연구하는 등 다양한 연구를 통해 LLM의 레이블링 성능을 내부 직원 수준까지 끌어올리는 데 집중합니다.
연구 결과 중 의미 있는 성과는 논문이나 오픈소스 형태로 외부에 공개하기도 합니다. 논문 출판을 목표로 하지는 않지만, 제품 문제를 해결하는 과정에서 기존 연구로 충분히 설명되지 않는 부분이 있을 경우 이를 정리해 연구 성과로 남깁니다(
참고
). 지금까지 약 20여 건의 대외 연구 성과를 만들어 왔습니다.
AI로 비즈니스 문제를 해결하기 위해서는 모델 학습을 위한 인프라도 제대로 갖추어져야 합니다. HYPERCONNECT AI에서는 ML Research Scientist들이 충분히 모델 개발 및 실험을 진행할 수 있도록 자체적인 연구용 GPU 클러스터를 구축하여 활용하고 있습니다.
[ML Research Scientist 직무 소개]
HYPERCONNECT AI의 ML Research Scientist는 제품의 문제를 연구 문제로 바라보고 해결합니다. 문제 정의, 가설 수립, 모델 선택과 설계, 실험, 성과 분석까지 전 과정을 주도하며, 연구 결과가 실제 제품 지표 개선으로 이어지는 것을 목표로 합니다. 외부에서 이미 정의된 문제를 푸는 것이 아니라, HYPERCONNECT의 데이터와 제약 조건에 맞게 문제를 다시 정의합니다. 공개된 다양한 접근 방법과 기존 연구를 폭넓게 검토한 뒤, 상황에 맞는 해법을 선택하거나 새롭게 만들어냅니다. 반복적인 실험과 검증을 통해 제품에서 의미 있는 신호를 찾아내는 것이 이 역할의 핵심입니다(
참고).
연구 과정에서는 PM 및 소프트웨어 엔지니어 등 다양한 직군과 협업하지만, 연구 방향과 핵심 판단은 스스로 책임집니다. 단일 모델의 성능 개선을 넘어서, 시간이 지날수록 더 큰 임팩트를 낼 수 있는 구조를 만들어 가는 것을 중요하게 생각합니다. 데이터/백엔드 엔지니어링은 전담조직과 협업해 진행합니다.
제출해 주신 내용 중 허위 사실이 있거나 관련법 상 근로제공에 결격사유가 있는 경우 채용이 취소될 수 있으며, 필요시 사전에 안내된 채용 절차 외에도 추가 전형 및 서류 확인이 진행될 수 있습니다.
국가보훈대상자는 관계 법령에 따라 우대하오니, 해당되시는 분께서는 지원 시 고지해주시고 채용 시 증빙서류를 제출해주시기 바랍니다.
하이퍼커넥트가 채용하는 포지션에 지원하는 경우, 개인정보 처리에 관하여서는 본 개인정보처리방침이 적용됩니다:
https://career.hyperconnect.com/privacy
#HPCNT
Requirements
ML관련분야박사학위보유자또는석사학위보유자로서4년이상의관련분야연구경험을보유하신분복잡하고정답이정해지지않은비즈니스문제를ML문제로바꾸어풀수있는분강력한오너십으로연구전과정을주도적으로추진하실수있는분비즈니스임팩트를극대화하는방향으로연구마일스톤을설정하고전략적의사결정을하실수있는분여러직군의이해관계자와협업할수있는커뮤니케이션능력을갖추신분한개이상의ML도메인에대한깊이있는경험(arel
=
"noopenernoreferrer"class
=
"postings-link"href
=
"https:hyperconnect.github.io20241021beyond-collaborative-filtering.html"참고)과탄탄한MLfoundation을보유하신분성장에대한강한의지가있으시며,지속적으로성장한경험이있으신분한국어로원활한의사소통이가능하신분
Preferred Qualifications
AIML탑티어학회(NeurIPS,ICLR,ICML,CVPR,KDD등)에이론적인기여가포함된논문을게재한경험이있으신분연구팀혹은엔지니어링팀리드경험이있거나팀원들을성장시킨경험이있으신분(공동1저자또는교신저자경험포함)PMPO혹은그에준하는포지션으로유저경험을향상시켜본경험이있으신분인과관계분석및기타통계기법을사용하여데이터에서의미있는통찰력을발굴하고의사결정에올바르게적용하실수있는분클라이언트(Android,iOS),백엔드를포함해AIML분야외개발경험이풍부하신분이해관계자를설득할수있는비즈니스레벨의영어를구사하실수있는분
고용형태/채용절차
고용형태:정규직채용절차:서류전형&gt;코딩테스트&amp;과제전형&gt;1차면접&gt;2차면접&gt;3차면접(해당시)&gt;최종합격서류전형의경우합격자에한하여개별안내드릴예정입니다.지원서류:자유양식의상세경력기반영문이력서(PDF)